// pricingConfig.js — V6 revised plan definitions, USD + INR only.

// India-first: USD for all other regions, INR for Indian users.
export const CURRENCIES = ["USD", "INR"];

// INR prices are BASE prices (pre-GST). 18% GST is added at checkout time.
// price_inr_annual = promotional annual INR per month (base, pre-GST) — fixed rate

export const CURRENCY_META = {
  USD: { symbol: "$",  label: "US Dollar",   flag: "🇺🇸" },
  INR: { symbol: "₹", label: "Indian Rupee", flag: "🇮🇳" },
};

// price_usd         = monthly USD price
// price_usd_annual  = annual plan price per month (USD, ~20% off)
// price_inr         = monthly INR price (base, pre-GST — 18% GST added at checkout)
// price_inr_annual  = promotional annual price per month (INR, base, pre-GST) — fixed rate
// trialCredit       = once-only signup extraction credit (Free plan only)
export const PLANS = [
  {
    id: "free",
    name: "Free",
    price_usd: 0,
    price_usd_annual: 0,
    price_inr: 0,
    price_inr_annual: 0,
    period: "month",
    tagline: "Try DatIQ risk-free",
    badge: null,
    highlight: false,
    trialCredit: 25,
    limits: {
      extractions: 10,
      enrichments_per_extraction: Infinity,
      exports: ["csv"],
      email_export: false,
      scheduled_monitoring: 0,
      team_seats: 1,
      extra_seat_usd: null,
      api_access: false,
      white_label_pdf: false,
      priority_support: false,
      workspaces: 1,
      batch_max_urls: 5,
    },
    features: [
      { label: "10 extractions / month",        included: true },
      { label: "Full AI features",              included: true },
      { label: "CSV export",                    included: true },
      { label: "25-extraction trial credit",    included: true },
      { label: "Batch mode (up to 5 URLs)",     included: true },
      { label: "PDF export",                    included: false },
      { label: "Markdown / JSON export",        included: false },
      { label: "Email export",                  included: false },
      { label: "Scheduled monitoring",          included: false },
      { label: "API access",                    included: false },
      { label: "White-label PDF",               included: false },
    ],
  },
  {
    id: "go",
    name: "Go",
    price_usd: 4.8,
    price_usd_annual: 4,
    price_inr: 359,
    price_inr_annual: 299,
    period: "month",
    tagline: "Your first step up from Free",
    badge: null,
    highlight: false,
    limits: {
      extractions: 200,
      enrichments_per_extraction: Infinity,
      exports: ["csv", "pdf", "markdown"],
      email_export: true,
      scheduled_monitoring: 0,
      team_seats: 1,
      extra_seat_usd: null,
      api_access: false,
      white_label_pdf: false,
      priority_support: false,
      workspaces: 1,
      batch_max_urls: 20,
    },
    features: [
      { label: "200 extractions / month",          included: true },
      { label: "All enrichments",                  included: true },
      { label: "CSV + PDF + Markdown export",      included: true },
      { label: "Email export",                     included: true },
      { label: "Batch mode (up to 20 URLs)",       included: true },
      { label: "Scheduled monitoring",             included: false },
      { label: "JSON export",                      included: false },
      { label: "API access",                       included: false },
      { label: "White-label PDF",                  included: false },
    ],
  },
  {
    id: "select",
    name: "Select",
    price_usd: 14.4,
    price_usd_annual: 12,
    price_inr: 1199,
    price_inr_annual: 999,
    period: "month",
    tagline: "For individuals & freelancers",
    badge: null,
    highlight: false,
    limits: {
      extractions: 500,
      enrichments_per_extraction: Infinity,
      exports: ["csv", "pdf", "markdown"],
      email_export: true,
      scheduled_monitoring: 0,
      team_seats: 1,
      extra_seat_usd: null,
      api_access: false,
      white_label_pdf: false,
      priority_support: false,
      workspaces: 1,
      batch_max_urls: 50,
    },
    features: [
      { label: "500 extractions / month",          included: true },
      { label: "All enrichments",                  included: true },
      { label: "CSV + PDF + Markdown export",      included: true },
      { label: "Email export",                     included: true },
      { label: "Batch mode (up to 50 URLs)",       included: true },
      { label: "Scheduled monitoring",             included: false },
      { label: "JSON export",                      included: false },
      { label: "API access",                       included: false },
      { label: "White-label PDF",                  included: false },
    ],
  },
  {
    id: "pro",
    name: "Pro",
    price_usd: 20.4,
    price_usd_annual: 17,
    price_inr: 1799,
    price_inr_annual: 1499,
    period: "month",
    tagline: "For power users & consultants",
    badge: "Recommended",
    highlight: true,
    limits: {
      extractions: 1000,
      enrichments_per_extraction: Infinity,
      exports: ["csv", "pdf", "markdown", "json"],
      email_export: true,
      scheduled_monitoring: 1,
      team_seats: 1,
      extra_seat_usd: null,
      api_access: false,
      white_label_pdf: false,
      priority_support: false,
      workspaces: 1,
      batch_max_urls: 100,
    },
    features: [
      { label: "1,000 extractions / month",        included: true },
      { label: "All enrichments",                  included: true },
      { label: "CSV + PDF + Markdown + JSON",      included: true },
      { label: "Email export",                     included: true },
      { label: "Batch mode (up to 100 URLs)",      included: true },
      { label: "1 scheduled monitor",              included: true },
      { label: "Google Sheets push",               included: true },
      { label: "API access",                       included: false },
      { label: "White-label PDF",                  included: false },
    ],
  },
  {
    id: "business",
    name: "Business",
    price_usd: 44.4,
    price_usd_annual: 37,
    price_inr: 4199,
    price_inr_annual: 3499,
    period: "month",
    tagline: "For teams and growing agencies",
    badge: null,
    highlight: false,
    limits: {
      extractions: 10000,
      enrichments_per_extraction: Infinity,
      exports: ["csv", "pdf", "markdown", "json"],
      email_export: true,
      scheduled_monitoring: 5,
      team_seats: 3,
      extra_seat_usd: 9,
      api_access: true,
      // Business now ships with the white-label PDF + priority support that
      // were previously Agency-only (2026-08-02). Both flags are surfaced in
      // the PricingMatrix, the entitlement model, and the white-label template
      // storage layer so the feature parity is real, not just a label.
      white_label_pdf: true,
      priority_support: true,
      workspaces: 1,
      batch_max_urls: 250,
    },
    features: [
      { label: "10,000 extractions / month",       included: true },
      { label: "All enrichments",                  included: true },
      { label: "CSV + PDF + Markdown + JSON",      included: true },
      { label: "Email export",                     included: true },
      { label: "Batch mode (up to 250 URLs)",      included: true },
      { label: "CSV import enrichment",            included: true },
      { label: "5 scheduled monitors",             included: true },
      { label: "API access",                       included: true },
      { label: "3 seats + HubSpot CRM sync",       included: true },
      { label: "White-label PDF",                  included: true },
      { label: "Priority support",                 included: true },
    ],
  },
  {
    id: "agency",
    name: "Agency",
    price_usd: 106.8,
    price_usd_annual: 89,
    price_inr: 10199,
    price_inr_annual: 8499,
    period: "month",
    tagline: "Unlimited scale, your brand",
    badge: "Best Value",
    highlight: false,
    limits: {
      extractions: Infinity,
      enrichments_per_extraction: Infinity,
      exports: ["csv", "pdf", "markdown", "json"],
      email_export: true,
      scheduled_monitoring: Infinity,
      team_seats: 5,
      extra_seat_usd: null,
      api_access: true,
      white_label_pdf: true,
      priority_support: true,
      workspaces: 5,
      batch_max_urls: 500,
    },
    features: [
      { label: "Unlimited extractions",            included: true },
      { label: "All enrichments",                  included: true },
      { label: "CSV + PDF + Markdown + JSON",      included: true },
      { label: "Email export",                     included: true },
      { label: "Batch mode (up to 500 URLs)",      included: true },
      { label: "CSV import enrichment",            included: true },
      { label: "Unlimited scheduled monitoring",   included: true },
      { label: "API access",                       included: true },
      { label: "5 client workspaces",              included: true },
      { label: "White-label PDF",                  included: true },
      { label: "Slack routing",                    included: true },
      { label: "Priority support",                 included: true },
    ],
  },
  {
    id: "developer",
    name: "Developer",
    price_usd: 32.4,
    price_usd_annual: 27,
    price_inr: 2999,
    price_inr_annual: 2499,
    period: "month",
    tagline: "API-first, 10K row credits",
    badge: "Coming H3 2026",
    highlight: false,
    comingSoon: true,
    limits: {
      extractions: 10000,
      enrichments_per_extraction: Infinity,
      exports: ["csv", "pdf", "markdown", "json", "jsonl"],
      email_export: true,
      scheduled_monitoring: 0,
      team_seats: 1,
      extra_seat_usd: null,
      api_access: true,
      white_label_pdf: false,
      priority_support: false,
      workspaces: 1,
      batch_max_urls: 500,
    },
    features: [
      { label: "10,000 row credits / month",   included: true },
      { label: "API access (no UI required)",  included: true },
      { label: "Batch mode (up to 500 URLs)",  included: true },
      { label: "CSV import enrichment",        included: true },
      { label: "JSONL / RAG export",           included: true },
      { label: "Webhook push",                 included: true },
      { label: "All enrichments",              included: true },
      { label: "Scheduled monitoring",         included: false },
      { label: "Team seats",                   included: false },
      { label: "White-label PDF",              included: false },
    ],
  },
];

// Enterprise plan — custom pricing, displayed separately
export const ENTERPRISE_PLAN = {
  id: "enterprise",
  name: "Enterprise",
  tagline: "Custom (≥ $1,000 / mo)",
  badge: null,
  features: [
    { label: "Custom extraction volume",      included: true },
    { label: "SSO / SAML",                   included: true },
    { label: "DPA & SLA",                    included: true },
    { label: "On-prem deployment option",    included: true },
    { label: "Dedicated support engineer",   included: true },
    { label: "Custom integrations",          included: true },
  ],
};

export const PLAN_BY_ID = Object.fromEntries(PLANS.map((p) => [p.id, p]));

// All price_inr are BASE prices (pre-GST). 18% GST added at checkout.
// hidden: true → not shown in top-up section on Pricing page.
export const TOPUP_BUNDLES = [
  {
    id: "extractions-bundle",
    name: "Extractions Bundle",
    icon: "zap",
    price_usd: 9,
    price_inr: 749,
    description: "100 extra extractions with all enrichments, CSV + PDF, and email export.",
    unit: "per 100 extractions",
    bonusExtractions: 100,
    stackable: true,
  },
  {
    id: "batch-pack",
    name: "Batch Pack",
    icon: "layers",
    price_usd: 9,
    price_inr: 749,
    description: "Unlock batch mode for 50 URLs. Run multi-URL extractions with combined CSV/JSON/Markdown output. Stackable in multiples of 50.",
    unit: "per 50 URLs",
    stackable: true,
    bonusBatchUrls: 50,
    hidden: true,           // hidden from the Pricing page top-up section
  },
  {
    id: "scheduler-addon",
    name: "Scheduled Monitor",
    icon: "clock",
    price_usd: 5,
    price_inr: 399,
    description: "Monitor one URL daily — email alert when content changes are detected.",
    unit: "per URL / month",
    stackable: true,
  },
  {
    id: "workspace-addon",
    name: "Extra Workspace",
    icon: "briefcase",
    price_usd: 19,
    price_inr: 1499,
    // An extra workspace gets the same features as the user's current plan
    // (extractions, exports, enrichments, API access, white-label PDF, etc.)
    // but is bounded by the parent plan's team_seats cap. So on Business
    // (3 seats), each extra workspace can invite at most 3 members. This
    // is intentional: workspace add-ons scale capacity, not headcount.
    description: "Adds a fully-featured client workspace — same plan features as your current tier, capped at your plan's team-seats limit (e.g. 3 seats on Business).",
    unit: "/ month",
    stackable: true,
    // Feature-parity with the parent plan is enforced by the entitlement
    // model (entitlementModel.js — see `workspaceAddonFeaturesForPlan`).
    // The add-on itself does NOT carry plan features; it inherits them.
    inheritsParentPlanFeatures: true,
    cappedByParentTeamSeats: true,
  },
];
