// resolve-company.js — turn a typed company NAME into a confirmed domain.
//
//   POST /api/resolve-company { name }  →  { candidates: [...], best }
//
// Backs the "type a company name" field on the template runner. The candidate
// list is generated by the PURE resolver (src/lib/templates/companyResolver.js)
// and CONFIRMED here by actually fetching each candidate — we never claim a
// domain we have not seen respond and whose page did not corroborate the name.
//
// ── BOUNDED BY CONSTRUCTION ─────────────────────────────────────────────────
// This is a convenience field on a form. It must never become a crawler:
//   • at most MAX_CANDIDATES fetches per call
//   • a hard per-fetch timeout, and a hard TOTAL budget
//   • stops at the first CONFIRMED match — the common case costs one fetch
//   • only the first 12KB of any response is read, enough for <head>
// A field that can spend an unbounded number of requests on a typo is a field
// that will, and the user typing is not the one who pays for it.
//
// ── NO CREDITS ARE CHARGED ──────────────────────────────────────────────────
// Deliberately. This runs while someone is still deciding what to research;
// billing for a lookup they may abandon would make the smart field more
// expensive than typing the domain, which defeats it entirely.

import { candidateDomains, judge, bestOf } from "../../src/lib/templates/companyResolver.js";
import { isPublicHttpUrl } from "./lib/publicUrl.js";

const HEADERS = {
  "Content-Type": "application/json",
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "Content-Type, Authorization",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
  "Cache-Control": "no-store",
};
const json = (statusCode, body) => ({ statusCode, headers: HEADERS, body: JSON.stringify(body) });

const MAX_CANDIDATES = 5;
const PER_FETCH_MS = 3500;
const TOTAL_BUDGET_MS = 9000;   // under Netlify's 10s synchronous ceiling
const MAX_BYTES = 12_000;
const MAX_NAME = 120;

/** Read just enough of a page to identify it. Never throws. */
async function peek(domain, signal) {
  const url = `https://${domain}`;
  // The same SSRF gate every other outbound fetch in this codebase passes
  // through — a guessed domain is still attacker-influenced input.
  if (!(await isPublicHttpUrl(url))) return null;
  try {
    const res = await fetch(url, { signal, redirect: "follow", headers: { "User-Agent": "DatIQBot/1.0" } });
    if (!res.ok) return null;
    const reader = res.body?.getReader?.();
    let html = "";
    if (reader) {
      let received = 0;
      while (received < MAX_BYTES) {
        const { done, value } = await reader.read();
        if (done) break;
        received += value.length;
        html += new TextDecoder().decode(value, { stream: true });
      }
      try { await reader.cancel(); } catch { /* already done */ }
    } else {
      html = (await res.text()).slice(0, MAX_BYTES);
    }
    const pick = (re) => (html.match(re)?.[1] || "").trim().slice(0, 300);
    return {
      title: pick(/<title[^>]*>([^<]*)</i),
      siteName: pick(/<meta[^>]+property=["']og:site_name["'][^>]+content=["']([^"']*)["']/i),
      description: pick(/<meta[^>]+name=["']description["'][^>]+content=["']([^"']*)["']/i),
    };
  } catch {
    return null;
  }
}

export const handler = async (event) => {
  if (event.httpMethod === "OPTIONS") return { statusCode: 204, headers: HEADERS, body: "" };
  if (event.httpMethod !== "POST") return json(405, { error: "Method not allowed" });

  let body;
  try { body = JSON.parse(event.body || "{}"); } catch { return json(400, { error: "Invalid JSON body" }); }

  const name = String(body.name || "").trim().slice(0, MAX_NAME);
  if (!name) return json(400, { error: "name is required" });

  const candidates = candidateDomains(name, { max: MAX_CANDIDATES });
  if (!candidates.length) return json(200, { candidates: [], best: null, name });

  const deadline = Date.now() + TOTAL_BUDGET_MS;
  const results = [];

  for (const domain of candidates) {
    if (Date.now() >= deadline) break;
    const controller = new AbortController();
    const t = setTimeout(() => controller.abort(), Math.min(PER_FETCH_MS, deadline - Date.now()));
    let page = null;
    try { page = await peek(domain, controller.signal); } finally { clearTimeout(t); }
    if (!page) continue;
    const verdict = judge(name, domain, page);
    results.push(verdict);
    // Stop at the first CONFIRMED match: the page corroborated the name, and
    // continuing would spend fetches to re-answer a settled question.
    if (verdict.confirmed) break;
  }

  return json(200, {
    name,
    candidates: results,
    // May be null, and the UI must handle that as "type it yourself" rather
    // than as an error. A miss is the expected outcome for any company whose
    // domain does not derive from its name.
    best: bestOf(results),
    tried: candidates.length,
  });
};
