// src/components/BrandKitEditor.integration.test.jsx
// The structured Brand Kit form inside WhiteLabelTemplateUploader — Phase 2
// of the export-branding feature, additive alongside the existing raw-PDF
// white-label upload (covered separately in
// WhiteLabelTemplateUploader.integration.test.jsx).

import { describe, expect, it, vi, beforeEach } from "vitest";
import { act, fireEvent, render, screen } from "@testing-library/react";
import WhiteLabelTemplateUploader from "./WhiteLabelTemplateUploader.jsx";
import { readBrandKit } from "../lib/whiteLabelTemplate.js";

beforeEach(() => {
  localStorage.clear();
});

function pdfInput() {
  return document.querySelector('input[type=file][accept="application/pdf"]');
}
function logoInput() {
  return document.querySelector('input[type=file]:not([accept="application/pdf"])');
}

describe("Brand Kit editor", () => {
  it("renders with every field blank when nothing is saved yet", () => {
    render(<WhiteLabelTemplateUploader canManage={true} />);
    expect(screen.getByPlaceholderText("Acme Research Co.")).toHaveValue("");
    expect(readBrandKit()).toBeNull();
  });

  it("saves a filled-in kit and it round-trips through readBrandKit()", async () => {
    render(<WhiteLabelTemplateUploader canManage={true} />);
    fireEvent.change(screen.getByPlaceholderText("Acme Research Co."), { target: { value: "Acme Research Co." } });
    fireEvent.change(screen.getByPlaceholderText("Market Intelligence, Delivered."), { target: { value: "Data, delivered." } });
    fireEvent.click(screen.getByRole("button", { name: /save brand kit/i }));
    expect(await screen.findByText(/brand kit saved/i)).toBeInTheDocument();
    const saved = readBrandKit();
    expect(saved.companyName).toBe("Acme Research Co.");
    expect(saved.tagline).toBe("Data, delivered.");
  });

  it("shows a validation error and does not save an invalid field", async () => {
    render(<WhiteLabelTemplateUploader canManage={true} />);
    fireEvent.change(screen.getByPlaceholderText("#4f46e5"), { target: { value: "not-a-color" } });
    fireEvent.click(screen.getByRole("button", { name: /save brand kit/i }));
    expect(await screen.findByText(/accent color must be a hex value/i)).toBeInTheDocument();
    expect(readBrandKit()).toBeNull();
  });

  it("the live Markdown preview is generated by the real export renderer and reflects the typed company name", async () => {
    render(<WhiteLabelTemplateUploader canManage={true} />);
    fireEvent.change(screen.getByPlaceholderText("Acme Research Co."), { target: { value: "Acme Research Co." } });
    fireEvent.click(screen.getByText(/Markdown\/CSV\/JSON preview/i));
    expect(screen.getByText(/# Acme Research Co\. Extraction Report/)).toBeInTheDocument();
  });

  it("the preview always keeps the 'Powered by DatIQ' line — no field can remove it", async () => {
    render(<WhiteLabelTemplateUploader canManage={true} />);
    fireEvent.change(screen.getByPlaceholderText("Acme Research Co."), { target: { value: "Acme Research Co." } });
    fireEvent.click(screen.getByText(/Markdown\/CSV\/JSON preview/i));
    // Appears in both the visual PDF-style preview and the Markdown preview.
    expect(screen.getAllByText(/Powered by DatIQ/).length).toBeGreaterThanOrEqual(2);
  });

  it("removes a saved brand kit on confirmation", async () => {
    render(<WhiteLabelTemplateUploader canManage={true} />);
    fireEvent.change(screen.getByPlaceholderText("Acme Research Co."), { target: { value: "Acme" } });
    fireEvent.click(screen.getByRole("button", { name: /save brand kit/i }));
    await screen.findByText(/brand kit saved/i);

    const originalConfirm = window.confirm;
    window.confirm = vi.fn(() => true);
    fireEvent.click(screen.getByRole("button", { name: /remove brand kit/i }));
    window.confirm = originalConfirm;

    expect(readBrandKit()).toBeNull();
    expect(screen.getByPlaceholderText("Acme Research Co.")).toHaveValue("");
  });

  it("uploading a logo shows a preview and it is included in the saved kit", async () => {
    class FakeFileReader {
      readAsDataURL() {
        queueMicrotask(() => {
          this.result = "data:image/png;base64,AAAA";
          this.onload?.();
        });
      }
    }
    globalThis.FileReader = FakeFileReader;
    // jsdom doesn't implement image decoding — stub Image so onload fires.
    class FakeImage {
      set src(_v) { queueMicrotask(() => this.onload?.()); }
    }
    globalThis.Image = FakeImage;

    render(<WhiteLabelTemplateUploader canManage={true} />);
    const file = { name: "logo.png", type: "image/png", size: 1000 };
    await act(async () => {
      fireEvent.change(logoInput(), { target: { files: [file] } });
      await new Promise((r) => setTimeout(r, 10));
    });
    expect(screen.getByAltText("Logo preview")).toBeInTheDocument();

    fireEvent.click(screen.getByRole("button", { name: /save brand kit/i }));
    await screen.findByText(/brand kit saved/i);
    expect(readBrandKit().logo.dataUrl).toBe("data:image/png;base64,AAAA");
  });

  it("still renders the Advanced (raw-PDF) section alongside the Brand Kit, unaffected", () => {
    render(<WhiteLabelTemplateUploader canManage={true} />);
    expect(screen.getByText(/Advanced: full-page PDF background/i)).toBeInTheDocument();
    expect(pdfInput()).not.toBeNull();
  });
});
