// Icon.jsx — thin wrapper over lucide-react that maps the design system's
// semantic icon names to Lucide components. Lets the rest of the app reference
// icons by name (e.g. <Icon name="bookmark" />), matching the original mockup.

import {
  ScanSearch,
  Fingerprint,
  Radar,
  SquareCheckBig,
  CircleSlash,
  Receipt,
  Link,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  Trash2,
  Download,
  ExternalLink,
  Sun,
  Moon,
  Plus,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  ChevronUp,
  Globe,
  LayoutGrid,
  Table,
  AlertTriangle,
  Clock,
  Hash,
  FileText,
  X,
  Check,
  CheckCircle2,
  Bookmark,
  Search,
  Copy,
  ListTree,
  Layers,
  Zap,
  Filter,
  Sparkles,
  Circle,
  Database,
  Mail,
  Send,
  Minus,
  Share2,
  Image,
  Users,
  Network,
  Wand2,
  Code2,
  ClipboardCopy,
  RotateCw,
  LogIn,
  LogOut,
  User,
  FlaskConical,
  Target,
  Eye,
  BarChart2,
  Building2,
  Linkedin,
  Twitter,
  Shield,
  PlayCircle,
  TrendingUp,
  Info,
  // V5 additions
  CreditCard,
  Tag,
  Gift,
  Crown,
  AlertCircle,
  ToggleLeft,
  ToggleRight,
  Calendar,
  DollarSign,
  Percent,
  // R0 additions
  BookOpen,
  Newspaper,
  Heart,
  Lightbulb,
  Rocket,
  Swords,
  MessageSquare,
  // R1 additions
  Compass,
  HelpCircle,
  Settings,
  SquarePen,
  UserCircle,
  UserPlus,
  MapPin,
  Repeat,
  Menu,
  Pin,
  PinOff,
  // Batch/export additions
  Upload,
  FileJson,
  FileCode,
  ListChecks,
  Layers2,
  Loader2,
  CheckSquare,
  XSquare,
  AlertOctagon,
  FileUp,
  Columns,
  Briefcase,
  IndianRupee,
  // Scheduler additions
  Pause,
  Bell,
  CalendarClock,
  // Quick Wins additions
  GitCompareArrows,
  History,
  SearchX,
  Type,
  Clock3,
  CopyPlus,
  Sheet,
  Folder,
  Inbox,
  FolderOpen,
  // Cloud BI Q1–Q11 additions
  Trophy,
  Library,
  LayoutList,
  BarChart3,
  ShieldAlert,
  ShoppingBag,
  Github,
  Command,
  ThumbsUp,
  ThumbsDown,
  Sparkle,
  MousePointerSquareDashed,
  PartyPopper,
  CircleCheckBig,
  ShieldCheck,
  Ban,
  Columns3,
  TrendingDown,
  // Workflows (workflow-implementation-and-optimization branch)
  RotateCcw,
  Timer,
  Activity,
  RefreshCw,
  MousePointerClick,
  // Ops monitoring (staging branch)
  Server,
  Gauge,
  // Team workspaces
  Lock,
} from "lucide-react";

const MAP = {
  link: Link,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up": ArrowUp,
  "arrow-up-right": ArrowUpRight,
  trash: Trash2,
  download: Download,
  external: ExternalLink,
  sun: Sun,
  moon: Moon,
  plus: Plus,
  "chevron-right": ChevronRight,
  receipt: Receipt,
  "chevron-left": ChevronLeft,
  "chevron-down": ChevronDown,
  globe: Globe,
  grid: LayoutGrid,
  table: Table,
  clock: Clock,
  hash: Hash,
  file: FileText,
  x: X,
  check: Check,
  "check-circle": CheckCircle2,
  "alert-triangle": AlertTriangle,
  bookmark: Bookmark,
  search: Search,
  copy: Copy,
  "list-tree": ListTree,
  layers: Layers,
  zap: Zap,
  filter: Filter,
  sparkles: Sparkles,
  "rotate-ccw": RotateCcw,
  timer: Timer,
  activity: Activity,
  "refresh-cw": RefreshCw,
  "mouse-pointer-click": MousePointerClick,
  dot: Circle,
  database: Database,
  mail: Mail,
  send: Send,
  minus: Minus,
  share: Share2,
  image: Image,
  users: Users,
  network: Network,
  map: Network,
  wand: Wand2,
  code: Code2,
  "clipboard-copy": ClipboardCopy,
  refresh: RotateCw,
  "log-in": LogIn,
  "log-out": LogOut,
  user: User,
  flask: FlaskConical,
  target: Target,
  eye: Eye,
  "bar-chart": BarChart2,
  building: Building2,
  linkedin: Linkedin,
  twitter: Twitter,
  shield: Shield,
  "play-circle": PlayCircle,
  "trending-up": TrendingUp,
  info: Info,
  "chevron-up": ChevronUp,
  // V5
  "credit-card": CreditCard,
  tag: Tag,
  gift: Gift,
  crown: Crown,
  "alert-circle": AlertCircle,
  "toggle-left": ToggleLeft,
  "toggle-right": ToggleRight,
  calendar: Calendar,
  "dollar-sign": DollarSign,
  percent: Percent,
  // R0
  "book-open": BookOpen,
  newspaper: Newspaper,
  heart: Heart,
  lightbulb: Lightbulb,
  rocket: Rocket,
  swords: Swords,
  "message-square": MessageSquare,
  // R1
  compass: Compass,
  "help-circle": HelpCircle,
  settings: Settings,
  edit: SquarePen,
  "user-circle": UserCircle,
  "user-plus": UserPlus,
  "map-pin": MapPin,
  repeat: Repeat,
  menu: Menu,
  pin: Pin,
  "pin-off": PinOff,
  // Batch/export
  upload: Upload,
  "file-json": FileJson,
  "file-code": FileCode,
  "list-checks": ListChecks,
  "layers-2": Layers2,
  loader: Loader2,
  "check-square": CheckSquare,
  "x-square": XSquare,
  "alert-octagon": AlertOctagon,
  "file-up": FileUp,
  columns: Columns,
  briefcase: Briefcase,
  "indian-rupee": IndianRupee,
  // Scheduler
  pause: Pause,
  bell: Bell,
  "calendar-clock": CalendarClock,
  // Quick Wins — content presets
  "git-compare": GitCompareArrows,
  // Quick Wins — recent extractions widget
  history: History,
  "search-x": SearchX,
  // Quick Wins — extraction charts
  type: Type,
  "clock-3": Clock3,
  // Quick Wins — Scrape Similar
  "copy-plus": CopyPlus,
  // Quick Wins — Open in Google Sheets
  sheet: Sheet,
  // Groke QW#2/#3 — tags + collections
  tag: Tag,
  hash: Hash,
  folder: Folder,
  "rotate-cw": RotateCw,
  inbox: Inbox,
  "folder-open": FolderOpen,
  // Cloud BI Q1–Q11 additions
  trophy: Trophy,
  library: Library,
  "layout-list": LayoutList,
  "bar-chart-3": BarChart3,
  "shield-alert": ShieldAlert,
  "shopping-bag": ShoppingBag,
  github: Github,
  // Q11 keyboard shortcuts
  command: Command,
  "thumbs-up": ThumbsUp,
  "thumbs-down": ThumbsDown,
  // Q4 / Q1 (alt) tour + demo
  sparkle: Sparkle,
  "pointer-square": MousePointerSquareDashed,
  party: PartyPopper,
  "check-big": CircleCheckBig,
  // F14 trust strip
  "shield-check": ShieldCheck,
  ban: Ban,
  // F13 pricing matrix
  "columns-3": Columns3,
  // FA3 paywall
  "trending-down": TrendingDown,
  // Ops monitoring (/admin/monitoring + /admin/health)
  activity: Activity,
  server: Server,
  gauge: Gauge,
  // Discoverability module (/discoverability). `target` already exists above.
  "scan-search": ScanSearch,
  fingerprint: Fingerprint,
  radar: Radar,
  "square-check-big": SquareCheckBig,
  "circle-slash": CircleSlash,
  lock: Lock,
};


export default function Icon({ name, size = 20, strokeWidth = 2, className, style }) {
  const Cmp = MAP[name] || Circle;
  return (
    <Cmp
      size={size}
      strokeWidth={strokeWidth}
      className={className}
      style={{ flexShrink: 0, display: "block", ...style }}
      aria-hidden="true"
    />
  );
}
