// Icon.jsx — thin wrapper over lucide-react that maps the design system's
// semantic icon names to Lucide components. Lets the rest of the app reference
// icons by name (e.g. <Icon name="bookmark" />), matching the original mockup.

import {
  Link,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Trash2,
  Download,
  ExternalLink,
  Sun,
  Moon,
  Plus,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  ChevronUp,
  Globe,
  LayoutGrid,
  Table,
  AlertTriangle,
  Clock,
  Hash,
  FileText,
  X,
  Check,
  CheckCircle2,
  Bookmark,
  Search,
  Copy,
  ListTree,
  Layers,
  Zap,
  Filter,
  Sparkles,
  Circle,
  Database,
  Mail,
  Send,
  Minus,
  Share2,
  Image,
  Users,
  Network,
  Wand2,
  Code2,
  ClipboardCopy,
  RotateCw,
  LogIn,
  LogOut,
  User,
  FlaskConical,
  Target,
  Eye,
  BarChart2,
  Building2,
  Linkedin,
  Twitter,
  Shield,
  PlayCircle,
  TrendingUp,
  Info,
  // V5 additions
  CreditCard,
  Tag,
  Gift,
  Crown,
  AlertCircle,
  ToggleLeft,
  ToggleRight,
  Calendar,
  DollarSign,
  Percent,
  // R0 additions
  BookOpen,
  Newspaper,
  Heart,
  Lightbulb,
  Rocket,
  MessageSquare,
  // R1 additions
  Compass,
  HelpCircle,
  Settings,
  SquarePen,
  UserCircle,
  UserPlus,
  MapPin,
  Repeat,
  Menu,
  Pin,
  PinOff,
  // Batch/export additions
  Upload,
  FileJson,
  FileCode,
  ListChecks,
  Layers2,
  Loader2,
  CheckSquare,
  XSquare,
  AlertOctagon,
  FileUp,
  Columns,
  Briefcase,
} from "lucide-react";

const MAP = {
  link: Link,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up-right": ArrowUpRight,
  trash: Trash2,
  download: Download,
  external: ExternalLink,
  sun: Sun,
  moon: Moon,
  plus: Plus,
  "chevron-right": ChevronRight,
  "chevron-left": ChevronLeft,
  "chevron-down": ChevronDown,
  globe: Globe,
  grid: LayoutGrid,
  table: Table,
  clock: Clock,
  hash: Hash,
  file: FileText,
  x: X,
  check: Check,
  "check-circle": CheckCircle2,
  "alert-triangle": AlertTriangle,
  bookmark: Bookmark,
  search: Search,
  copy: Copy,
  "list-tree": ListTree,
  layers: Layers,
  zap: Zap,
  filter: Filter,
  sparkles: Sparkles,
  dot: Circle,
  database: Database,
  mail: Mail,
  send: Send,
  minus: Minus,
  share: Share2,
  image: Image,
  users: Users,
  network: Network,
  map: Network,
  wand: Wand2,
  code: Code2,
  "clipboard-copy": ClipboardCopy,
  refresh: RotateCw,
  "log-in": LogIn,
  "log-out": LogOut,
  user: User,
  flask: FlaskConical,
  target: Target,
  eye: Eye,
  "bar-chart": BarChart2,
  building: Building2,
  linkedin: Linkedin,
  twitter: Twitter,
  shield: Shield,
  "play-circle": PlayCircle,
  "trending-up": TrendingUp,
  info: Info,
  "chevron-up": ChevronUp,
  // V5
  "credit-card": CreditCard,
  tag: Tag,
  gift: Gift,
  crown: Crown,
  "alert-circle": AlertCircle,
  "toggle-left": ToggleLeft,
  "toggle-right": ToggleRight,
  calendar: Calendar,
  "dollar-sign": DollarSign,
  percent: Percent,
  // R0
  "book-open": BookOpen,
  newspaper: Newspaper,
  heart: Heart,
  lightbulb: Lightbulb,
  rocket: Rocket,
  "message-square": MessageSquare,
  // R1
  compass: Compass,
  "help-circle": HelpCircle,
  settings: Settings,
  edit: SquarePen,
  "user-circle": UserCircle,
  "user-plus": UserPlus,
  "map-pin": MapPin,
  repeat: Repeat,
  menu: Menu,
  pin: Pin,
  "pin-off": PinOff,
  // Batch/export
  upload: Upload,
  "file-json": FileJson,
  "file-code": FileCode,
  "list-checks": ListChecks,
  "layers-2": Layers2,
  loader: Loader2,
  "check-square": CheckSquare,
  "x-square": XSquare,
  "alert-octagon": AlertOctagon,
  "file-up": FileUp,
  columns: Columns,
  briefcase: Briefcase,
};

export default function Icon({ name, size = 20, strokeWidth = 2, className, style }) {
  const Cmp = MAP[name] || Circle;
  return (
    <Cmp
      size={size}
      strokeWidth={strokeWidth}
      className={className}
      style={{ flexShrink: 0, display: "block", ...style }}
      aria-hidden="true"
    />
  );
}
