// scripts/build-sitemap.mjs — generate public/sitemap.xml from the route registry.
//
//   npm run build:sitemap
//   node scripts/build-sitemap.mjs --check    exit 1 if the committed file is stale
//
// ── Why generated ────────────────────────────────────────────────────────
// The hand-maintained sitemap had drifted from reality in both directions: it
// listed /what-is-datiq and /vs/battlecard (the latter serving a duplicate of
// the homepage), while omitting /vs/apify and /vs/phantombuster, which existed
// and were being maintained. Driving it from scripts/site-routes.mjs — the same
// list the prerenderer uses — makes both kinds of drift impossible.
//
// ── Why <lastmod> ────────────────────────────────────────────────────────
// The previous sitemap had none at all. It is the strongest signal a crawler
// has for "this changed, come back", and its absence is a large part of why
// changes took so long to surface. Rather than stamping every URL with today's
// date — which is a lie that crawlers learn to ignore — each entry takes the
// git commit date of the file that actually produces it.

import { writeFileSync, readFileSync, existsSync, readdirSync } from "node:fs";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { execSync } from "node:child_process";
import {
  REACT_OWNED, STATIC_OWNED, HELP_INDEX, generatedFileFor,
} from "./site-routes.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const PUBLIC = join(ROOT, "public");
const OUT = join(PUBLIC, "sitemap.xml");
const ORIGIN = "https://datiq.app";
const CHECK = process.argv.includes("--check");

/**
 * Last git commit date for a path, as YYYY-MM-DD. Falls back to today only if
 * git cannot answer (a brand-new, uncommitted file).
 */
function gitLastMod(relPath) {
  try {
    const out = execSync(`git log -1 --format=%cs -- "${relPath}"`, {
      cwd: ROOT, encoding: "utf8", stdio: ["ignore", "pipe", "ignore"],
    }).trim();
    if (/^\d{4}-\d{2}-\d{2}$/.test(out)) return out;
  } catch { /* not a git repo, or untracked */ }
  return new Date().toISOString().slice(0, 10);
}

const entries = [];

for (const r of REACT_OWNED) {
  // The source of truth for a React-owned page's content is its component, but
  // the file that actually gets crawled is the prerendered HTML — so date the
  // entry from whichever moved most recently.
  const generated = r.prerender === false ? "index.html" : join("public", generatedFileFor(r.path));
  entries.push({
    loc: `${ORIGIN}${r.path}`,
    lastmod: gitLastMod(generated),
    changefreq: r.changefreq,
    priority: r.priority,
  });
}

for (const s of STATIC_OWNED) {
  entries.push({
    loc: `${ORIGIN}${s.path}`,
    lastmod: gitLastMod(join("public", s.file)),
    changefreq: s.changefreq,
    priority: s.priority,
  });
}

// The help site: its index plus every generated article. These were absent
// from the sitemap entirely, and the index was listed as /help/index.html
// rather than the /help/ directory form that everything links to.
const helpDir = join(PUBLIC, "help");
const helpFiles = existsSync(helpDir)
  ? readdirSync(helpDir).filter((f) => f.endsWith(".html")).sort()
  : [];
for (const f of helpFiles) {
  const isIndex = f === "index.html";
  entries.push({
    loc: `${ORIGIN}/help/${isIndex ? "" : f}`,
    lastmod: gitLastMod(join("public", "help", f)),
    changefreq: isIndex ? HELP_INDEX.changefreq : "monthly",
    priority: isIndex ? HELP_INDEX.priority : "0.5",
  });
}

const xml =
  `<?xml version="1.0" encoding="UTF-8"?>\n` +
  `<!-- GENERATED by scripts/build-sitemap.mjs from scripts/site-routes.mjs.\n` +
  `     Do not hand-edit: run \`npm run build:sitemap\`.\n` +
  `     lastmod is each file's git commit date, not the build date. -->\n` +
  `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
  entries
    .map(
      (e) =>
        `  <url>\n` +
        `    <loc>${e.loc}</loc>\n` +
        `    <lastmod>${e.lastmod}</lastmod>\n` +
        `    <changefreq>${e.changefreq}</changefreq>\n` +
        `    <priority>${e.priority}</priority>\n` +
        `  </url>`,
    )
    .join("\n") +
  `\n</urlset>\n`;

if (CHECK) {
  const prev = existsSync(OUT) ? readFileSync(OUT, "utf8") : "";
  if (prev !== xml) {
    console.log("[sitemap] stale — run: npm run build:sitemap");
    process.exit(1);
  }
  console.log(`[sitemap] up to date · ${entries.length} URLs`);
} else {
  writeFileSync(OUT, xml, "utf8");
  console.log(`[sitemap] wrote ${entries.length} URLs to public/sitemap.xml`);
}
