// scripts/page-ownership.test.mjs — the ownership table as an assertion.
//
// scripts/site-routes.mjs declares who owns each URL. Without this file that
// declaration is a comment, and comments drift: the situation it describes
// arose precisely because twenty URLs were owned twice and nothing checked.
//
// Each test below corresponds to a defect that actually shipped.

import { describe, it, expect } from "vitest";
import { readFileSync, existsSync } from "node:fs";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  REACT_OWNED, STATIC_OWNED, PRIVATE_PREFIXES, REDIRECTS,
  prerenderableRoutes, generatedFileFor,
} from "./site-routes.mjs";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const PUBLIC = join(ROOT, "public");
const appJsx = readFileSync(join(ROOT, "src/App.jsx"), "utf8");
const toml = readFileSync(join(ROOT, "netlify.toml"), "utf8");
const robots = readFileSync(join(PUBLIC, "robots.txt"), "utf8");

const declaredRoutes = new Set(
  [...appJsx.matchAll(/path="([^"]*)"/g)].map((m) => m[1]).filter((p) => p.startsWith("/")),
);

describe("page ownership — React-owned routes", () => {
  it("every React-owned URL has a declared <Route>", () => {
    const missing = REACT_OWNED.filter((r) => !declaredRoutes.has(r.path)).map((r) => r.path);
    expect(missing).toEqual([]);
  });

  it("every prerenderable route has a generated file", () => {
    const missing = prerenderableRoutes()
      .filter((r) => !existsSync(join(PUBLIC, generatedFileFor(r.path))))
      .map((r) => r.path);
    expect(missing).toEqual([]);
  });

  it("generated files carry the do-not-edit banner", () => {
    // A generated file without the banner is one somebody hand-edited, and the
    // next `npm run prerender` will silently throw that edit away.
    const unbannered = prerenderableRoutes()
      .filter((r) => {
        const f = join(PUBLIC, generatedFileFor(r.path));
        return existsSync(f) && !readFileSync(f, "utf8").includes("GENERATED by scripts/prerender.mjs");
      })
      .map((r) => r.path);
    expect(unbannered).toEqual([]);
  });

  it("no generated file canonicalises to the homepage", () => {
    // THE defect. index.html hard-codes canonical="https://datiq.app/", and any
    // route that fails to override it tells Google it IS the homepage — which
    // is how /privacy, /terms and /vs/battlecard left the index.
    const wrong = [];
    for (const r of prerenderableRoutes()) {
      const f = join(PUBLIC, generatedFileFor(r.path));
      if (!existsSync(f)) continue;
      const m = readFileSync(f, "utf8").match(/<link[^>]+rel="canonical"[^>]+href="([^"]+)"/);
      const want = `https://datiq.app${r.path}`;
      if (!m) wrong.push(`${r.path}: none`);
      else if (m[1] !== want) wrong.push(`${r.path}: ${m[1]}`);
    }
    expect(wrong).toEqual([]);
  });

  it("the homepage is never prerendered", () => {
    // public/index.html would be copied over dist/index.html by Vite, replacing
    // the app's entry point with a snapshot of itself.
    expect(prerenderableRoutes().some((r) => r.path === "/")).toBe(false);
    expect(existsSync(join(PUBLIC, "index.html"))).toBe(false);
    expect(() => generatedFileFor("/")).toThrow();
  });
});

describe("page ownership — static-owned pages", () => {
  it("every static-owned URL has a hand-written file", () => {
    const missing = STATIC_OWNED.filter((s) => !existsSync(join(PUBLIC, s.file))).map((s) => s.path);
    expect(missing).toEqual([]);
  });

  it("no static-owned URL also has a React route that renders", () => {
    // Owning a URL twice is the whole problem. /about, /pricing and eighteen
    // others served different documents depending on how you arrived.
    // `redirectOnly` routes are exempt: they render null and only bounce the
    // browser to the static file, so there is still one document.
    const doubled = STATIC_OWNED
      .filter((s) => !s.redirectOnly && declaredRoutes.has(s.path))
      .map((s) => s.path);
    expect(doubled).toEqual([]);
  });

  it("redirect-only routes really do nothing but redirect", () => {
    // Guards the exemption above: if one of these ever grows real markup it
    // becomes a second document for that URL and the test must stop excusing it.
    for (const s of STATIC_OWNED.filter((x) => x.redirectOnly)) {
      const name = appJsx.match(
        new RegExp(`path="${s.path.replace(/\//g, "\\/")}"\\s+element=\\{<(\\w+)`),
      )?.[1];
      expect(name, `no element for ${s.path}`).toBeTruthy();
      const body = appJsx.slice(appJsx.indexOf(`function ${name}(`));
      const fn = body.slice(0, body.indexOf("\n}") + 2);
      expect(fn, `${name} should redirect`).toMatch(/window\.location/);
      expect(fn, `${name} should render nothing`).toMatch(/return null/);
    }
  });

  it("static-owned files are not prerender output", () => {
    const clobbered = STATIC_OWNED.filter((s) => {
      const f = join(PUBLIC, s.file);
      return existsSync(f) && readFileSync(f, "utf8").includes("GENERATED by scripts/prerender.mjs");
    }).map((s) => s.path);
    expect(clobbered).toEqual([]);
  });

  it("no URL appears in both ownership lists", () => {
    const react = new Set(REACT_OWNED.map((r) => r.path));
    const both = STATIC_OWNED.filter((s) => react.has(s.path)).map((s) => s.path);
    expect(both).toEqual([]);
  });
});

describe("/vs — five detail pages, one hub", () => {
  const DETAIL = ["browse-ai", "clay", "firecrawl", "apify", "phantombuster"];

  it("all five comparisons exist in directory form", () => {
    const missing = DETAIL.filter((s) => !existsSync(join(PUBLIC, "vs", s, "index.html")));
    expect(missing).toEqual([]);
  });

  it("no loose .html duplicates remain under /vs", () => {
    // public/vs/firecrawl.html and vs/firecrawl/index.html were byte-identical
    // and both served, competing for the same query.
    const loose = [...DETAIL, "compare"].filter((s) => existsSync(join(PUBLIC, "vs", `${s}.html`)));
    expect(loose).toEqual([]);
  });

  it("the hub links to every detail page", () => {
    // The old hand-written table listed Browse.ai and Clay only, while all five
    // pages existed and were being maintained.
    const hub = readFileSync(join(ROOT, "src/pages/VsCompare.jsx"), "utf8");
    const missing = DETAIL.filter((s) => !hub.includes(`/vs/${s}`));
    expect(missing).toEqual([]);
  });
});

describe("redirects", () => {
  it("every retired URL has a 301 in netlify.toml", () => {
    const missing = REDIRECTS.filter((r) => !toml.includes(`from = "${r.from}"`)).map((r) => r.from);
    expect(missing).toEqual([]);
  });

  it("each redirect points where the registry says", () => {
    for (const r of REDIRECTS) {
      const block = toml.slice(toml.indexOf(`from = "${r.from}"`));
      expect(block.slice(0, 200)).toContain(`to = "${r.to}"`);
    }
  });

  it("no redirect target is itself retired", () => {
    // A -> B -> C chains lose ranking signal at every hop and are a common
    // outcome of retiring URLs one at a time.
    const froms = new Set(REDIRECTS.map((r) => r.from));
    const chained = REDIRECTS.filter((r) => froms.has(r.to)).map((r) => `${r.from} -> ${r.to}`);
    expect(chained).toEqual([]);
  });
});

describe("private routes are excluded everywhere", () => {
  const appRoutes = PRIVATE_PREFIXES.filter((p) => p !== "/admin");

  it("netlify.toml sends X-Robots-Tag noindex for each", () => {
    const missing = appRoutes.filter((p) => !toml.includes(`for = "${p}"`) && !toml.includes(`for = "${p}/*"`));
    expect(missing).toEqual([]);
  });

  it("robots.txt disallows each", () => {
    const missing = PRIVATE_PREFIXES.filter((p) => !robots.includes(`Disallow: ${p}`));
    expect(missing).toEqual([]);
  });

  it("index.html's inline guard covers the same list", () => {
    const html = readFileSync(join(ROOT, "index.html"), "utf8");
    const missing = PRIVATE_PREFIXES.filter((p) => !html.includes(`"${p}"`));
    expect(missing).toEqual([]);
  });

  it("no private route is in the sitemap", () => {
    const sitemap = readFileSync(join(PUBLIC, "sitemap.xml"), "utf8");
    const leaked = PRIVATE_PREFIXES.filter((p) => sitemap.includes(`<loc>https://datiq.app${p}`));
    expect(leaked).toEqual([]);
  });
});

describe("robots.txt structure", () => {
  it("has exactly one wildcard group", () => {
    // Two `User-agent: *` groups is non-standard. Google merges them, but a
    // spec-following crawler takes only the last matching group — which here
    // would have silently dropped the /api/ disallow.
    const count = (robots.match(/^User-agent: \*$/gm) || []).length;
    expect(count).toBe(1);
  });

  it("every named bot group repeats the admin disallow", () => {
    // A named group REPLACES the wildcard group for that crawler rather than
    // extending it, so an Allow-only group hands that bot the admin console.
    const groups = robots.split(/^User-agent: /m).slice(1);
    const leaky = groups
      .filter((g) => !g.startsWith("*"))
      .filter((g) => !g.includes("Disallow: /admin"))
      .map((g) => g.split("\n")[0]);
    expect(leaky).toEqual([]);
  });

  it("points at the sitemap", () => {
    expect(robots).toContain("Sitemap: https://datiq.app/sitemap.xml");
  });
});
