// scripts/prerender.mjs — render every React-owned route to static HTML.
//
//   npm run prerender            build, render, write public/<route>/index.html
//   npm run prerender -- --check verify the committed output is not stale
//
// Output is COMMITTED, like docs/build-help.mjs's output. It is not generated
// during the Netlify build, deliberately: that would download Chromium on every
// cold build and make a deploy fail on a browser-install hiccup. The pre-push
// hook enforces freshness instead (see scripts/pre-push.sh).
//
// Uses system Chrome via channel:"chrome", the same approach as
// docs/capture-screenshots.mjs, so there is no Playwright browser download.
//
// ╔══════════════════════════════════════════════════════════════════════════╗
// ║ THE TRAP — read before touching serveDist().                             ║
// ║                                                                          ║
// ║ Output lands in public/, and Netlify serves public/ files BEFORE the SPA  ║
// ║ fallback — that is the whole point. But it means that on the second run,  ║
// ║ a naive static server would serve public/pricing/index.html when asked    ║
// ║ for /pricing, and we would be prerendering our OWN PREVIOUS OUTPUT.       ║
// ║ Each run would re-render a re-render; the HTML would degrade a little     ║
// ║ every time and nothing would ever error.                                  ║
// ║                                                                          ║
// ║ serveDist() therefore FORCES index.html for every prerenderable route,    ║
// ║ ignoring any generated file. scripts/prerender.test.mjs asserts this.     ║
// ╚══════════════════════════════════════════════════════════════════════════╝

import { chromium } from "playwright";
import { createServer } from "node:http";
import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync, statSync } from "node:fs";
import { dirname, join, extname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { execSync } from "node:child_process";
import { prerenderableRoutes, generatedFileFor } from "./site-routes.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const DIST = join(ROOT, "dist");
const PUBLIC = join(ROOT, "public");
const CHECK = process.argv.includes("--check");
const PORT = Number(process.env.PRERENDER_PORT || 4319);

export const BANNER =
  "<!-- GENERATED by scripts/prerender.mjs — do not edit. " +
  "Edit the React page and run `npm run prerender`. -->";

const MIME = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".mjs": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".ico": "image/x-icon",
  ".woff2": "font/woff2",
  ".txt": "text/plain; charset=utf-8",
  ".xml": "application/xml; charset=utf-8",
};

/**
 * The set of paths that MUST be served the SPA shell rather than any file that
 * happens to sit at that path. Exported so the test can assert the behaviour
 * without booting a browser.
 */
export function forcedShellPaths() {
  return new Set(prerenderableRoutes().map((r) => r.path));
}

/**
 * Static server over dist/, with the one critical exception described in the
 * banner above.
 */
export function serveDist(distDir, { forced = forcedShellPaths() } = {}) {
  const shell = join(distDir, "index.html");
  return createServer((req, res) => {
    const url = new URL(req.url, "http://localhost");
    const pathname = decodeURIComponent(url.pathname);

    // THE TRAP GUARD. Never let a previously generated file answer for a route
    // we are about to regenerate.
    if (forced.has(pathname) || forced.has(pathname.replace(/\/$/, ""))) {
      res.writeHead(200, { "Content-Type": MIME[".html"] });
      res.end(readFileSync(shell));
      return;
    }

    let filePath = join(distDir, pathname);
    try {
      if (existsSync(filePath) && statSync(filePath).isDirectory()) {
        filePath = join(filePath, "index.html");
      }
      if (existsSync(filePath) && statSync(filePath).isFile()) {
        res.writeHead(200, { "Content-Type": MIME[extname(filePath)] || "application/octet-stream" });
        res.end(readFileSync(filePath));
        return;
      }
    } catch { /* fall through to the shell */ }

    // SPA fallback, matching netlify.toml's `/* → /index.html 200`.
    res.writeHead(200, { "Content-Type": MIME[".html"] });
    res.end(readFileSync(shell));
  });
}

/** Strip the volatile bits so a re-run with no real change produces no diff. */
export function normalizeHtml(html) {
  return String(html)
    // React dev/prod both leave these; they are not content.
    .replace(/\s+data-reactroot=""/g, "")
    // Our own prerender marker, re-added on write.
    .replace(/<!--\s*GENERATED by scripts\/prerender\.mjs[\s\S]*?-->\n?/g, "")
    .trimEnd();
}

async function renderAll() {
  const routes = prerenderableRoutes();
  const server = serveDist(DIST);
  await new Promise((r) => server.listen(PORT, r));

  const browser = await chromium.launch({ channel: "chrome", headless: true });
  const ctx = await browser.newContext({
    viewport: { width: 1280, height: 900 },
    // Pin the timezone and locale. currencyService.detectCurrency() reads the
    // timezone, so without this the crawlable /pricing HTML would bake in
    // whichever currency the machine running the script happened to be in.
    timezoneId: "UTC",
    locale: "en-US",
  });

  // Render the page a first-time, signed-out visitor sees — with the consent
  // banner present (no stored choice) and the onboarding tour suppressed, since
  // its full-screen backdrop would otherwise be captured over every page.
  await ctx.addInitScript(() => {
    try {
      localStorage.clear();
      localStorage.setItem(
        "datiq.onboardingTour.v1",
        JSON.stringify({ completedAt: new Date("2026-01-01T00:00:00Z").toISOString() }),
      );
    } catch { /* storage unavailable */ }
  });

  const page = await ctx.newPage();
  const results = [];

  for (const route of routes) {
    const rel = generatedFileFor(route.path);
    const outFile = join(PUBLIC, rel);
    try {
      await page.goto(`http://localhost:${PORT}${route.path}`, {
        waitUntil: "networkidle",
        timeout: 30000,
      });
      // useSeo writes the title/canonical in an effect, so wait for the real
      // title rather than the shell's default before capturing.
      await page
        .waitForFunction(
          () => document.title && document.title !== "DatIQ: The Unified Web Intelligence Platform | Intelligence from Web",
          { timeout: 5000 },
        )
        .catch(() => { /* the homepage-titled routes are legitimately rare */ });

      const html = await page.content();
      const canonical = await page
        .$eval('link[rel="canonical"]', (el) => el.getAttribute("href"))
        .catch(() => null);
      const title = await page.title();

      results.push({ route: route.path, rel, outFile, html, canonical, title });
    } catch (err) {
      results.push({ route: route.path, rel, outFile, error: err.message });
    }
  }

  await browser.close();
  await new Promise((r) => server.close(r));
  return results;
}

function writeOut({ outFile, html }) {
  mkdirSync(dirname(outFile), { recursive: true });
  const body = `${BANNER}\n${normalizeHtml(html)}\n`;
  const prev = existsSync(outFile) ? readFileSync(outFile, "utf8") : null;
  if (prev === body) return false;
  writeFileSync(outFile, body, "utf8");
  return true;
}

function ensureBuild() {
  if (!existsSync(join(DIST, "index.html"))) {
    console.log("[prerender] dist/ missing — running vite build first");
  }
  // Always rebuild: prerendering a stale bundle is worse than a slow script.
  execSync("npx vite build", { cwd: ROOT, stdio: "inherit" });
}

const isMain = process.argv[1] && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url));
if (isMain) {
  ensureBuild();
  const results = await renderAll();

  const failed = results.filter((r) => r.error);
  const ok = results.filter((r) => !r.error);

  // A route that renders but keeps the homepage canonical is the exact defect
  // this whole exercise exists to fix, so it is a hard failure, not a warning.
  const wrongCanonical = ok.filter(
    (r) => r.canonical && r.canonical !== `https://datiq.app${r.route === "/" ? "/" : r.route}`,
  );
  const noCanonical = ok.filter((r) => !r.canonical);

  let changed = 0;
  if (!CHECK) {
    for (const r of ok) if (writeOut(r)) changed++;
  } else {
    for (const r of ok) {
      const body = `${BANNER}\n${normalizeHtml(r.html)}\n`;
      const prev = existsSync(r.outFile) ? readFileSync(r.outFile, "utf8") : null;
      if (prev !== body) { changed++; console.log(`  stale: ${r.route}`); }
    }
  }

  console.log(`\n[prerender] ${ok.length} rendered · ${changed} ${CHECK ? "stale" : "written"} · ${failed.length} failed`);
  for (const f of failed) console.log(`  ✗ ${f.route} — ${f.error}`);
  for (const w of wrongCanonical) console.log(`  ✗ ${w.route} — canonical is ${w.canonical}`);
  for (const n of noCanonical) console.log(`  ✗ ${n.route} — no canonical`);

  const bad = failed.length + wrongCanonical.length + noCanonical.length;
  if (bad) process.exit(1);
  if (CHECK && changed) {
    console.log("\nPrerendered output is stale. Run: npm run prerender");
    process.exit(1);
  }
}
