// scripts/prerender.mjs — render every React-owned route to static HTML.
//
//   npm run prerender            build, render, write public/<route>/index.html
//   npm run prerender -- --check verify the committed output is not stale
//
// Output is COMMITTED, like docs/build-help.mjs's output. It is not generated
// during the Netlify build, deliberately: that would download Chromium on every
// cold build and make a deploy fail on a browser-install hiccup. The pre-push
// hook enforces freshness instead (see scripts/pre-push.sh).
//
// Uses system Chrome via channel:"chrome", the same approach as
// docs/capture-screenshots.mjs, so there is no Playwright browser download.
//
// ╔══════════════════════════════════════════════════════════════════════════╗
// ║ THE TRAP — read before touching serveDist().                             ║
// ║                                                                          ║
// ║ Output lands in public/, and Netlify serves public/ files BEFORE the SPA  ║
// ║ fallback — that is the whole point. But it means that on the second run,  ║
// ║ a naive static server would serve public/pricing/index.html when asked    ║
// ║ for /pricing, and we would be prerendering our OWN PREVIOUS OUTPUT.       ║
// ║ Each run would re-render a re-render; the HTML would degrade a little     ║
// ║ every time and nothing would ever error.                                  ║
// ║                                                                          ║
// ║ serveDist() therefore FORCES index.html for every prerenderable route,    ║
// ║ ignoring any generated file. scripts/prerender.test.mjs asserts this.     ║
// ╚══════════════════════════════════════════════════════════════════════════╝

import { chromium } from "playwright";
import { createServer } from "node:http";
import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync, statSync } from "node:fs";
import { dirname, join, extname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { execSync } from "node:child_process";
import { prerenderableRoutes, generatedFileFor } from "./site-routes.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const DIST = join(ROOT, "dist");
const PUBLIC = join(ROOT, "public");
const CHECK = process.argv.includes("--check");
const PORT = Number(process.env.PRERENDER_PORT || 4319);

export const BANNER =
  "<!-- GENERATED by scripts/prerender.mjs — do not edit. " +
  "Edit the React page and run `npm run prerender`. -->";

const MIME = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".mjs": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".ico": "image/x-icon",
  ".woff2": "font/woff2",
  ".txt": "text/plain; charset=utf-8",
  ".xml": "application/xml; charset=utf-8",
};

/**
 * The set of paths that MUST be served the SPA shell rather than any file that
 * happens to sit at that path. Exported so the test can assert the behaviour
 * without booting a browser.
 */
export function forcedShellPaths() {
  return new Set(prerenderableRoutes().map((r) => r.path));
}

/**
 * Static server over dist/, with the one critical exception described in the
 * banner above.
 */
export function serveDist(distDir, { forced = forcedShellPaths() } = {}) {
  const shell = join(distDir, "index.html");
  return createServer((req, res) => {
    const url = new URL(req.url, "http://localhost");
    const pathname = decodeURIComponent(url.pathname);

    // THE TRAP GUARD. Never let a previously generated file answer for a route
    // we are about to regenerate.
    if (forced.has(pathname) || forced.has(pathname.replace(/\/$/, ""))) {
      res.writeHead(200, { "Content-Type": MIME[".html"] });
      res.end(readFileSync(shell));
      return;
    }

    let filePath = join(distDir, pathname);
    try {
      if (existsSync(filePath) && statSync(filePath).isDirectory()) {
        filePath = join(filePath, "index.html");
      }
      if (existsSync(filePath) && statSync(filePath).isFile()) {
        res.writeHead(200, { "Content-Type": MIME[extname(filePath)] || "application/octet-stream" });
        res.end(readFileSync(filePath));
        return;
      }
    } catch { /* fall through to the shell */ }

    // SPA fallback, matching netlify.toml's `/* → /index.html 200`.
    res.writeHead(200, { "Content-Type": MIME[".html"] });
    res.end(readFileSync(shell));
  });
}

/** Strip the volatile bits so a re-run with no real change produces no diff. */
export function normalizeHtml(html) {
  // Repeat until nothing changes: removing one element can bring two halves of
  // another together (CodeQL js/incomplete-multi-character-sanitization), and a
  // single pass would then leave a <script> or <iframe> behind.
  let out = String(html);
  for (let i = 0; i < 10; i++) {
    const next = normalizeOnce(out);
    if (next === out) break;
    out = next;
  }
  return out;
}

function normalizeOnce(html) {
  return String(html)
    // React dev/prod both leave these; they are not content.
    .replace(/\s+data-reactroot=""/g, "")
    // Our own prerender marker, re-added on write.
    .replace(/<!--\s*GENERATED by scripts\/prerender\.mjs[\s\S]*?-->\n?/g, "")
    // The private-route guard from index.html. It exists to noindex the
    // signed-in application, and a prerendered page is BY DEFINITION a public
    // one — so it can never fire here, and all it would do is publish the
    // internal route list (/admin, /dashboard, /account…) into every
    // marketing page's HTML. The release-readiness audit flags exactly that,
    // correctly. The real enforcement is netlify.toml's X-Robots-Tag anyway;
    // the inline guard only ever mattered for the un-prerendered shell.
    // NB: the attribute must be matched loosely. It is authored as a bare
    // boolean in index.html, but the browser serialises it as
    // data-datiq-private-guard="" in outerHTML — so an exact `<script attr>`
    // match silently fails and the guard ships anyway.
    .replace(/<script[^>]*\bdata-datiq-private-guard\b[^>]*>[\s\S]*?<\/script>\s*/gi, "")
    // Razorpay's checkout SDK pre-mounts a hidden container + iframe as soon as
    // it loads, which on /pricing means the captured HTML contained:
    //   * a `position:fixed; width:100%; height:100%` overlay,
    //   * a "Test Mode" badge,
    //   * Razorpay build hashes, and
    //   * a `unified_session_id` that changes on EVERY render.
    // The last of those alone made /pricing permanently "stale", which would
    // have had the pre-push gate crying wolf until someone disabled it. But the
    // rest is worse: none of it is content, a full-screen fixed overlay in
    // static HTML is a rendering hazard before React boots, and "Test Mode" is
    // not a thing to serve crawlers. The SDK re-creates all of it at runtime.
    // Strip the iframe FIRST and by its own tag. A `<div …>[\s\S]*?</div>`
    // match closes on the first nested </div>, which orphans the iframe rather
    // than removing it — leaving exactly the volatile session id behind.
    .replace(/<iframe[^>]*razorpay[^>]*>[\s\S]*?<\/iframe>\s*/gi, "")
    .replace(/<div class="razorpay-container"[\s\S]*?<\/div>\s*(?=<|$)/gi, "")
    .replace(/<div class="razorpay-backdrop"[^>]*>[\s\S]*?<\/div>\s*/gi, "")
    .trimEnd();
}

async function renderAll() {
  const routes = prerenderableRoutes();
  const server = serveDist(DIST);
  await new Promise((r) => server.listen(PORT, r));

  // System Chrome first — that is what docs/capture-screenshots.mjs uses and it
  // avoids a Playwright browser download on a dev machine. But `channel:"chrome"`
  // is a hard failure when Chrome is not installed, and this script now also runs
  // in CI as a freshness gate. Fall back to Playwright's own chromium so a missing
  // system Chrome degrades to a slower run rather than a red build.
  //
  // Third tier: PRERENDER_CHROMIUM_PATH. Some container images ship a Chromium
  // build whose revision does not match the one this Playwright version expects,
  // so the bundled fallback ALSO fails ("Executable doesn't exist at
  // .../chromium_headless_shell-<rev>/..."). That is an environment mismatch, not
  // a repo problem, and it must not be the reason a marketing page ships without
  // prerendered HTML — these pages exist precisely so crawlers that do not run JS
  // can read them. Point this at a working binary and the run proceeds.
  let browser;
  const explicitPath = process.env.PRERENDER_CHROMIUM_PATH;
  try {
    browser = explicitPath
      ? await chromium.launch({ executablePath: explicitPath, headless: true })
      : await chromium.launch({ channel: "chrome", headless: true });
  } catch (err) {
    console.warn(`  ${explicitPath ? "PRERENDER_CHROMIUM_PATH" : "system Chrome"} unavailable (${err.message.split("\n")[0]}) — falling back to bundled chromium`);
    browser = await chromium.launch({ headless: true });
  }
  const ctx = await browser.newContext({
    viewport: { width: 1280, height: 900 },
    // Pin the timezone and locale. currencyService.detectCurrency() reads the
    // timezone, so without this the crawlable /pricing HTML would bake in
    // whichever currency the machine running the script happened to be in.
    timezoneId: "UTC",
    locale: "en-US",
  });

  // Render the page a first-time, signed-out visitor sees — with the consent
  // banner present (no stored choice) and the onboarding tour suppressed, since
  // its full-screen backdrop would otherwise be captured over every page.
  await ctx.addInitScript(() => {
    try {
      localStorage.clear();
      localStorage.setItem(
        "datiq.onboardingTour.v1",
        JSON.stringify({ completedAt: new Date("2026-01-01T00:00:00Z").toISOString() }),
      );
      localStorage.setItem(
        "datiq.discoverabilityTour.v1",
        JSON.stringify({ completedAt: new Date("2026-01-01T00:00:00Z").toISOString() }),
      );
    } catch { /* storage unavailable */ }
  });

  const page = await ctx.newPage();
  const results = [];

  for (const route of routes) {
    const rel = generatedFileFor(route.path);
    const outFile = join(PUBLIC, rel);
    try {
      await page.goto(`http://localhost:${PORT}${route.path}`, {
        waitUntil: "networkidle",
        timeout: 30000,
      });
      // Wait for React to mount rather than comparing against a brand string:
      // the shell and Home now intentionally share the same rebrand title.
      await page
        .waitForFunction(
          () => Boolean(document.querySelector("#root .app-root")) && Boolean(document.title),
          { timeout: 5000 },
        )
        .catch(() => { /* the homepage-titled routes are legitimately rare */ });

      const html = await page.content();
      const canonical = await page
        .$eval('link[rel="canonical"]', (el) => el.getAttribute("href"))
        .catch(() => null);
      const title = await page.title();

      results.push({ route: route.path, rel, outFile, html, canonical, title });
    } catch (err) {
      results.push({ route: route.path, rel, outFile, error: err.message });
    }
  }

  await browser.close();
  await new Promise((r) => server.close(r));
  return results;
}

function writeOut({ outFile, html }) {
  mkdirSync(dirname(outFile), { recursive: true });
  const body = `${BANNER}\n${normalizeHtml(html)}\n`;
  const prev = existsSync(outFile) ? readFileSync(outFile, "utf8") : null;
  if (prev === body) return false;
  writeFileSync(outFile, body, "utf8");
  return true;
}

function ensureBuild() {
  if (!existsSync(join(DIST, "index.html"))) {
    console.log("[prerender] dist/ missing — running vite build first");
  }
  // Always rebuild: prerendering a stale bundle is worse than a slow script.
  execSync("npx vite build", { cwd: ROOT, stdio: "inherit" });
}

const isMain = process.argv[1] && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url));
if (isMain) {
  ensureBuild();
  const results = await renderAll();

  const failed = results.filter((r) => r.error);
  const ok = results.filter((r) => !r.error);

  // A route that renders but keeps the homepage canonical is the exact defect
  // this whole exercise exists to fix, so it is a hard failure, not a warning.
  const wrongCanonical = ok.filter(
    (r) => r.canonical && r.canonical !== `https://datiq.app${r.route === "/" ? "/" : r.route}`,
  );
  const noCanonical = ok.filter((r) => !r.canonical);

  let changed = 0;
  if (!CHECK) {
    for (const r of ok) if (writeOut(r)) changed++;
  } else {
    for (const r of ok) {
      const body = `${BANNER}\n${normalizeHtml(r.html)}\n`;
      const prev = existsSync(r.outFile) ? readFileSync(r.outFile, "utf8") : null;
      if (prev !== body) { changed++; console.log(`  stale: ${r.route}`); }
    }
  }

  console.log(`\n[prerender] ${ok.length} rendered · ${changed} ${CHECK ? "stale" : "written"} · ${failed.length} failed`);
  if (!CHECK && changed > 0) {
    // ⚠️ dist/ is now ONE GENERATION BEHIND. Vite copies public/ into dist/ at
    // BUILD time, and this script writes public/ AFTER its build — so
    // dist/<route>/index.html still holds the previous render and references
    // the previous asset hashes. Netlify is unaffected (it builds from the
    // COMMITTED public/), but serving dist/ locally right now tests stale HTML.
    console.log("           dist/ is stale until the next `npm run build` — rebuild before serving it locally.");
  }
  for (const f of failed) console.log(`  ✗ ${f.route} — ${f.error}`);
  for (const w of wrongCanonical) console.log(`  ✗ ${w.route} — canonical is ${w.canonical}`);
  for (const n of noCanonical) console.log(`  ✗ ${n.route} — no canonical`);

  const bad = failed.length + wrongCanonical.length + noCanonical.length;
  if (bad) process.exit(1);
  if (CHECK && changed) {
    console.log("\nPrerendered output is stale. Run: npm run prerender");
    process.exit(1);
  }
}
