// scripts/seo-homepage.test.mjs — the shipped bytes of the marketing pages.
//
// Asserted against the COMMITTED HTML, not against the React source, because
// what a crawler is served is the only thing that matters here and the two had
// silently disagreed for a year.
//
// ── WHAT A DISCOVERABILITY AUDIT OF datiq.app FOUND (2026-08-26) ───────────
//   AC-01  no passage is a self-contained answer of even 15 words
//   SH-10  the page has no heading elements at all
//   SH-01  the page has no H1
//   EA-04  no named author, in the markup or on the page
//   EA-06  no visible published or last-updated date
//   SH-09  no BreadcrumbList places the page within the site
//   AC-07  no heading is phrased as a question a reader would ask
//
// Six of the seven were one fact: `/` served `<div id="root"></div>` and
// nothing else, because it was the only public route excluded from
// prerendering. Scores were SEO 53.4, AEO 25.4, GEO 43.

import { describe, it, expect } from "vitest";
import { readFileSync, existsSync, readdirSync, statSync } from "node:fs";
import { join, dirname, resolve, relative } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const PUBLIC = join(ROOT, "public");
const HOME = join(PUBLIC, "home", "index.html");

const html = existsSync(HOME) ? readFileSync(HOME, "utf8") : "";
const body = html.slice(html.indexOf("<body"));

/** Visible text, with scripts and styles removed. */
function visibleText(source) {
  return source
    .replace(/<script[\s\S]*?<\/script>/g, " ")
    .replace(/<style[\s\S]*?<\/style>/g, " ")
    .replace(/<[^>]+>/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function jsonLdBlocks(source) {
  return [...source.matchAll(/<script type="application\/ld\+json"[^>]*>([\s\S]*?)<\/script>/g)]
    .map((m) => { try { return JSON.parse(m[1]); } catch { return null; } })
    .filter(Boolean);
}

function generatedPages(dir = PUBLIC, acc = []) {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) generatedPages(p, acc);
    else if (name === "index.html") {
      const h = readFileSync(p, "utf8");
      if (h.includes("GENERATED by scripts/prerender.mjs")) acc.push({ rel: relative(PUBLIC, p), html: h });
    }
  }
  return acc;
}

describe("homepage — is actually rendered", () => {
  it("exists as generated output", () => {
    expect(existsSync(HOME), "public/home/index.html missing — run npm run prerender").toBe(true);
    expect(html).toContain("GENERATED by scripts/prerender.mjs");
  });

  it("SH-01 — has exactly one H1", () => {
    expect((body.match(/<h1[\s>]/g) || []).length).toBe(1);
  });

  it("SH-10 — segments the page into headings", () => {
    // Was zero. A page with no structure is one undifferentiated chunk and
    // nothing in it can be retrieved on its own.
    expect((body.match(/<h2[\s>]/g) || []).length).toBeGreaterThanOrEqual(2);
  });

  it("AC-07 — at least one heading is phrased as a question", () => {
    const headings = [...body.matchAll(/<h[12][^>]*>([\s\S]*?)<\/h[12]>/g)]
      .map((m) => visibleText(m[1]));
    expect(headings.some((h) => h.includes("?")), `no question heading among: ${headings.join(" | ")}`).toBe(true);
  });

  it("serves real content, not a shell", () => {
    // The shell rendered ~10 words.
    expect(visibleText(body).split(" ").length).toBeGreaterThan(300);
  });

  it("canonicalises to the site root", () => {
    expect(html).toMatch(/rel="canonical"[^>]+href="https:\/\/datiq\.app\/"/);
  });
});

describe("homepage — the answer-first block (AC-01)", () => {
  const answer = (body.match(/class="[^"]*home-answer-block[^"]*"[^>]*>([\s\S]*?)<\/p>/) || [])[1];

  it("exists", () => {
    expect(answer, "no .home-answer-block in the shipped homepage").toBeTruthy();
  });

  it("is 40-60 words — long enough to answer, short enough to quote", () => {
    const words = visibleText(answer).split(" ").length;
    expect(words, `answer block is ${words} words`).toBeGreaterThanOrEqual(40);
    expect(words, `answer block is ${words} words`).toBeLessThanOrEqual(60);
  });

  it("names its subject rather than opening with a back-reference", () => {
    // It has to survive being quoted alone, with no page around it.
    const text = visibleText(answer);
    expect(text).toMatch(/^DatIQ\b/);
    expect(text.toLowerCase()).not.toMatch(/^(this|it|as mentioned|the platform)\b/);
  });
});

describe("homepage — trust signals", () => {
  const blocks = jsonLdBlocks(html);
  const webPage = blocks.find((b) => b["@type"] === "WebPage");

  it("EA-04 — declares a named author", () => {
    expect(webPage, "no WebPage JSON-LD on the homepage").toBeTruthy();
    expect(webPage.author?.name).toBeTruthy();
  });

  it("EA-04 — the author matches what the site visibly attributes", () => {
    // Schema naming somebody the page never shows is markup describing text a
    // reader cannot see — the SH-07 defect this product reports on others.
    // /about attributes DatIQ to the company, so the author is the company.
    const about = readFileSync(join(ROOT, "src/pages/About.jsx"), "utf8");
    expect(about).toContain(webPage.author.name);
  });

  it("EA-06 — carries a machine-readable dateModified", () => {
    expect(webPage.dateModified).toMatch(/^\d{4}-\d{2}-\d{2}$/);
  });

  it("EA-06 — shows the date to a reader too", () => {
    // Markup a reader cannot verify is the weaker half of this signal.
    expect(visibleText(body)).toMatch(/Last updated/i);
    expect(body).toMatch(/<time datetime="\d{4}-\d{2}-\d{2}"/i);
  });

  it("the visible date and dateModified agree", () => {
    const visible = (body.match(/<time datetime="(\d{4}-\d{2}-\d{2})"/i) || [])[1];
    expect(visible).toBe(webPage.dateModified);
  });
});

describe("SH-09 — BreadcrumbList across the whole site", () => {
  const pages = generatedPages();

  it("every generated page except the homepage has one", () => {
    const missing = pages
      .filter((p) => p.rel !== "home/index.html")
      .filter((p) => !jsonLdBlocks(p.html).some((b) => b["@type"] === "BreadcrumbList"))
      .map((p) => p.rel);
    expect(missing).toEqual([]);
  });

  it("no page has TWO", () => {
    // Eight pages hand-write their own in pageSeo.js. A page asserting two
    // different positions in the site hierarchy is worse than one asserting
    // none — a crawler is entitled to believe either.
    const dupes = pages
      .filter((p) => jsonLdBlocks(p.html).filter((b) => b["@type"] === "BreadcrumbList").length > 1)
      .map((p) => p.rel);
    expect(dupes).toEqual([]);
  });

  it("the homepage has none", () => {
    // A breadcrumb whose only item is the page itself describes nothing.
    expect(jsonLdBlocks(html).some((b) => b["@type"] === "BreadcrumbList")).toBe(false);
  });

  it("every breadcrumb starts at Home and ends at the page's own URL", () => {
    for (const page of pages) {
      const bc = jsonLdBlocks(page.html).find((b) => b["@type"] === "BreadcrumbList");
      if (!bc) continue;
      const items = bc.itemListElement;
      expect(items[0].name, page.rel).toBe("Home");
      expect(items[0].item, page.rel).toBe("https://datiq.app/");
      const canonical = (page.html.match(/rel="canonical"[^>]+href="([^"]+)"/) || [])[1];
      expect(items.at(-1).item, `${page.rel} breadcrumb tail vs canonical`).toBe(canonical);
    }
  });
});
