// scripts/site-routes.mjs — the single source of truth for what URLs this site
// has and WHO OWNS each one.
//
// Three consumers read this file and must never disagree:
//   * scripts/prerender.mjs        — renders every REACT_OWNED route to HTML
//   * scripts/build-sitemap.mjs    — lists REACT_OWNED + STATIC_OWNED
//   * scripts/page-ownership.test.mjs — asserts reality matches this list
//
// ── Why ownership is explicit ────────────────────────────────────────────
// This site used to serve TWENTY URLs from two different documents: a
// hand-written file under public/ for cold hits and crawlers, and a React page
// for in-app navigation. Same URL, two sources, maintained separately — and
// they had already drifted (llms.txt advertised prices the pricing page had
// not used for months). Every URL now has exactly one owner.
//
//   REACT_OWNED   the page is authored in JSX. Its static HTML is GENERATED by
//                 scripts/prerender.mjs and committed. Never hand-edit the
//                 generated file; edit the component and re-run the script.
//
//   STATIC_OWNED  the page is authored as hand-written HTML under public/.
//                 There is deliberately NO React route for it, and links to it
//                 are plain <a href> / external:true so the browser does a full
//                 load rather than falling through to the SPA's NotFound.
//
//   PRIVATE       the signed-in application. Never indexed, never prerendered,
//                 and must never keep index.html's root canonical — that is
//                 what got /privacy, /terms and /vs/battlecard dropped from
//                 Google's index as duplicates of the homepage.

/**
 * React-owned public routes, prerendered to public/<path>/index.html.
 *
 * `priority` and `changefreq` are sitemap hints only.
 */
export const REACT_OWNED = [
  // ⚠️ The homepage is NEVER prerendered. Its output file would be
  // public/index.html, and Vite copies public/ verbatim over the build output —
  // so it would overwrite dist/index.html, which is the app's actual entry
  // point. It also needs no help: `/` is the one route that already serves the
  // right title and canonical="https://datiq.app/" straight from the shell.
  { path: "/", priority: "1.0", changefreq: "daily", prerender: false },
  { path: "/pricing",                         priority: "0.9", changefreq: "weekly" },
  { path: "/about",                           priority: "0.7", changefreq: "monthly" },
  { path: "/contact",                         priority: "0.6", changefreq: "monthly" },
  { path: "/blog",                            priority: "0.8", changefreq: "weekly" },
  { path: "/changelog",                       priority: "0.6", changefreq: "weekly" },
  { path: "/gallery",                         priority: "0.6", changefreq: "weekly" },
  { path: "/integrations",                    priority: "0.8", changefreq: "monthly" },
  { path: "/privacy",                         priority: "0.4", changefreq: "yearly" },
  { path: "/terms",                           priority: "0.4", changefreq: "yearly" },

  // Use cases — all five URLs kept. Each targets its own query and each was
  // already indexed with a correct self-canonical; collapsing them into one
  // page would have surrendered four ranking landing pages. The duplication
  // that actually needed removing was the shared TEMPLATE, not the URLs.
  { path: "/use-cases",                       priority: "0.8", changefreq: "monthly" },
  { path: "/use-cases/lead-generation",       priority: "0.8", changefreq: "monthly" },
  { path: "/use-cases/competitor-research",   priority: "0.8", changefreq: "monthly" },
  { path: "/use-cases/seo-audit",             priority: "0.8", changefreq: "monthly" },
  { path: "/use-cases/market-research",       priority: "0.8", changefreq: "monthly" },

  // Programmatic pages — six URLs, three personas. for-* targets audience
  // queries ("DatIQ for sales teams"), extract-* targets task queries
  // ("extract contacts from any web page"). Same persona, different intent, so
  // they share one data model and cross-link rather than merging into one URL.
  { path: "/for-sales",                       priority: "0.7", changefreq: "monthly" },
  { path: "/for-seo",                         priority: "0.7", changefreq: "monthly" },
  { path: "/for-ci",                          priority: "0.7", changefreq: "monthly" },
  { path: "/extract-pricing",                 priority: "0.7", changefreq: "monthly" },
  { path: "/extract-contacts",                priority: "0.7", changefreq: "monthly" },
  { path: "/extract-headings",                priority: "0.7", changefreq: "monthly" },

  // The comparison HUB is React (it needs to stay in step with pricing and the
  // feature matrix); the five per-tool detail pages below it are static.
  { path: "/vs/compare",                      priority: "0.8", changefreq: "monthly" },
  { path: "/vs/battlecard",                   priority: "0.5", changefreq: "monthly" },
];

/**
 * Static-owned public URLs. Hand-written HTML under public/; no React route.
 * `file` is relative to public/ and is what page-ownership.test.mjs checks.
 */
export const STATIC_OWNED = [
  { path: "/faq",               file: "faq/index.html",               priority: "0.8", changefreq: "monthly" },
  // `redirectOnly`: App.jsx keeps a /dmca route, but it renders nothing — it
  // just sets window.location to the static file. That is a safety net for a
  // client-side navigation, NOT a second document competing for the URL, so it
  // does not count as double ownership. Any route flagged this way must render
  // null and do nothing but redirect; page-ownership.test.mjs enforces that.
  { path: "/dmca",              file: "dmca.html",                    priority: "0.3", changefreq: "yearly", redirectOnly: true },

  // The five per-tool comparisons, all in directory form so they share one
  // shape. Each is linked from the /vs/compare table.
  { path: "/vs/browse-ai",      file: "vs/browse-ai/index.html",      priority: "0.7", changefreq: "monthly" },
  { path: "/vs/clay",           file: "vs/clay/index.html",           priority: "0.7", changefreq: "monthly" },
  { path: "/vs/firecrawl",      file: "vs/firecrawl/index.html",      priority: "0.7", changefreq: "monthly" },
  { path: "/vs/apify",          file: "vs/apify/index.html",          priority: "0.7", changefreq: "monthly" },
  { path: "/vs/phantombuster",  file: "vs/phantombuster/index.html",  priority: "0.7", changefreq: "monthly" },
];

/**
 * The generated help site. Owned by docs/build-help.mjs, which renders it from
 * docs/DatIQ-User-Guide.md and docs/DatIQ-Developer-API.md — so it is neither
 * React-owned nor hand-written, and editing the HTML is always wrong.
 * Listed here so the sitemap includes it.
 */
export const HELP_INDEX = { path: "/help/", file: "help/index.html", priority: "0.7", changefreq: "monthly" };

/**
 * Signed-in application prefixes. noindex, never prerendered, canonical
 * stripped. Kept in sync by hand with three other places, deliberately — each
 * defends a different layer and any one of them alone is insufficient:
 *   * netlify.toml X-Robots-Tag headers  (works without JS — the real defence)
 *   * the inline guard in index.html      (belt-and-braces for JS crawlers)
 *   * public/robots.txt Disallow lines    (polite crawlers, pre-fetch)
 */
export const PRIVATE_PREFIXES = [
  "/admin",
  "/dashboard",
  "/account",
  "/preview",
  "/batch",
  "/schedules",
  "/workspace",
  "/collections",
  "/payment",
  "/reset-password",
  "/onboarding",
];

/**
 * Permanent redirects. Every URL that used to exist and now lives elsewhere.
 * Mirrored in netlify.toml; page-ownership.test.mjs asserts they match, so a
 * URL cannot be retired here without the redirect actually shipping.
 */
export const REDIRECTS = [
  // The duplicate Firecrawl page: public/vs/firecrawl.html AND
  // public/vs/firecrawl/index.html both existed and both served.
  { from: "/vs/firecrawl.html", to: "/vs/firecrawl" },
  // Normalised into directory form to match the other three comparisons.
  { from: "/vs/apify.html", to: "/vs/apify" },
  { from: "/vs/phantombuster.html", to: "/vs/phantombuster" },
  // The hub moved from a hand-written file to a React route.
  { from: "/vs/compare.html", to: "/vs/compare" },
  // Merged into the consolidated FAQ.
  { from: "/what-is-datiq", to: "/faq" },
  // build-help.mjs names pages after the section TITLE, so retitling section 14
  // to "Troubleshooting" moved this one file. The section NUMBER is unchanged,
  // so /help/15-* and /help/16-* keep their URLs.
  { from: "/help/14-faq-and-troubleshooting.html", to: "/help/14-troubleshooting.html" },
  // These were React <Navigate> redirects in App.jsx pointing at /vs/browse-ai.
  // That route is being deleted (the page is static-owned now), so they have to
  // become server-side redirects or they would dead-end in NotFound.
  { from: "/compare", to: "/vs/browse-ai" },
  { from: "/compare/*", to: "/vs/browse-ai" },
];

/** Convenience: every public URL, in sitemap order. */
export function allPublicRoutes() {
  return [...REACT_OWNED, ...STATIC_OWNED, HELP_INDEX];
}

/**
 * The React-owned routes that actually get a generated file. Excludes `/`
 * for the reason documented on its entry above.
 */
export function prerenderableRoutes() {
  return REACT_OWNED.filter((r) => r.prerender !== false);
}

/**
 * public/<dir>/index.html for a prerenderable route. Throws on "/" rather than
 * returning "index.html", because that path would clobber Vite's entry point
 * and a silent return here is how that bug would reach a build.
 */
export function generatedFileFor(routePath) {
  if (routePath === "/") {
    throw new Error(
      "generatedFileFor('/') — the homepage is not prerendered; " +
      "public/index.html would overwrite Vite's build entry. See site-routes.mjs.",
    );
  }
  return `${routePath.replace(/^\/+/, "").replace(/\/+$/, "")}/index.html`;
}
