// scripts/site-routes.mjs — the single source of truth for what URLs this site
// has and WHO OWNS each one.
//
// Three consumers read this file and must never disagree:
//   * scripts/prerender.mjs        — renders every REACT_OWNED route to HTML
//   * scripts/build-sitemap.mjs    — lists REACT_OWNED + STATIC_OWNED
//   * scripts/page-ownership.test.mjs — asserts reality matches this list
//
// ── Why ownership is explicit ────────────────────────────────────────────
// This site used to serve TWENTY URLs from two different documents: a
// hand-written file under public/ for cold hits and crawlers, and a React page
// for in-app navigation. Same URL, two sources, maintained separately — and
// they had already drifted (llms.txt advertised prices the pricing page had
// not used for months). Every URL now has exactly one owner.
//
//   REACT_OWNED   the page is authored in JSX. Its static HTML is GENERATED by
//                 scripts/prerender.mjs and committed. Never hand-edit the
//                 generated file; edit the component and re-run the script.
//
//   STATIC_OWNED  the page is authored as hand-written HTML under public/.
//                 There is deliberately NO React route for it, and links to it
//                 are plain <a href> / external:true so the browser does a full
//                 load rather than falling through to the SPA's NotFound.
//
//   PRIVATE       the signed-in application. Never indexed, never prerendered,
//                 and must never keep index.html's root canonical — that is
//                 what got /privacy, /terms and /vs/battlecard dropped from
//                 Google's index as duplicates of the homepage.

/**
 * React-owned public routes, prerendered to public/<path>/index.html.
 *
 * `priority` and `changefreq` are sitemap hints only.
 */
export const REACT_OWNED = [
  // ⚠️ The homepage IS prerendered, but NOT to public/index.html.
  //
  // The old reasoning was half right and half wrong, and the wrong half was
  // expensive. Right: public/index.html would be copied verbatim over
  // dist/index.html and clobber Vite's entry point, so that filename is still
  // forbidden — generatedFileFor() throws on any route that would derive it.
  // Wrong: "it needs no help". That was only ever true of the <head>. The
  // <body> of the shell is literally `<div id="root"></div>`, so the site's
  // highest-priority URL was the ONE public page serving no content at all.
  //
  // A discoverability audit of https://datiq.app on 2026-08-26 measured the
  // consequence: 10 rendered words, no H1, no headings, no answer passage, no
  // author, no dates — SEO 53.4, AEO 25.4, GEO 43. Five of its seven findings
  // were that one fact. Googlebot renders JavaScript eventually; GPTBot,
  // ClaudeBot, PerplexityBot and CCBot largely do not, so to the answer engines
  // this module exists to optimise for, the homepage was blank.
  //
  // So it renders to public/home/index.html and netlify.toml rewrites `/` to it
  // with status 200 + force (forced because dist/index.html is a real file at
  // `/` and would otherwise win). /home itself is noindexed and 301s to `/`,
  // and the generated file's own canonical is https://datiq.app/, so the helper
  // path cannot become a duplicate in the index.
  { path: "/", file: "home/index.html", priority: "1.0", changefreq: "daily" },
  { path: "/pricing",                         priority: "0.9", changefreq: "weekly" },
  { path: "/about",                           priority: "0.7", changefreq: "monthly" },
  { path: "/contact",                         priority: "0.6", changefreq: "monthly" },
  { path: "/blog",                            priority: "0.8", changefreq: "weekly" },
  { path: "/changelog",                       priority: "0.6", changefreq: "weekly" },
  { path: "/gallery",                         priority: "0.6", changefreq: "weekly" },
  { path: "/integrations",                    priority: "0.8", changefreq: "monthly" },
  { path: "/privacy",                         priority: "0.4", changefreq: "yearly" },
  { path: "/terms",                           priority: "0.4", changefreq: "yearly" },

  // Use cases — all five URLs kept. Each targets its own query and each was
  // already indexed with a correct self-canonical; collapsing them into one
  // page would have surrendered four ranking landing pages. The duplication
  // that actually needed removing was the shared TEMPLATE, not the URLs.
  { path: "/use-cases",                       priority: "0.8", changefreq: "monthly" },
  { path: "/use-cases/lead-generation",       priority: "0.8", changefreq: "monthly" },
  { path: "/use-cases/competitor-research",   priority: "0.8", changefreq: "monthly" },
  { path: "/use-cases/seo-audit",             priority: "0.8", changefreq: "monthly" },
  { path: "/use-cases/market-research",       priority: "0.8", changefreq: "monthly" },
  { path: "/use-cases/account-intelligence",   priority: "0.8", changefreq: "monthly" },
  { path: "/use-cases/competitive-monitoring", priority: "0.8", changefreq: "monthly" },
  { path: "/use-cases/ai-visibility",          priority: "0.8", changefreq: "monthly" },
  { path: "/use-cases/recruiting",             priority: "0.8", changefreq: "monthly" },
  { path: "/use-cases/investor-diligence",     priority: "0.8", changefreq: "monthly" },

  // Programmatic pages — six URLs, three personas. for-* targets audience
  // queries ("DatIQ for sales teams"), extract-* targets task queries
  // ("extract contacts from any web page"). Same persona, different intent, so
  // they share one data model and cross-link rather than merging into one URL.
  { path: "/for-sales",                       priority: "0.7", changefreq: "monthly" },
  { path: "/for-seo",                         priority: "0.7", changefreq: "monthly" },
  { path: "/for-ci",                          priority: "0.7", changefreq: "monthly" },
  { path: "/extract-pricing",                 priority: "0.7", changefreq: "monthly" },
  { path: "/extract-contacts",                priority: "0.7", changefreq: "monthly" },
  { path: "/extract-headings",                priority: "0.7", changefreq: "monthly" },

  // The comparison HUB is React (it needs to stay in step with pricing and the
  // feature matrix); the five per-tool detail pages below it are static.
  { path: "/vs/compare",                      priority: "0.8", changefreq: "monthly" },
  { path: "/vs/battlecard",                   priority: "0.5", changefreq: "monthly" },
];

/**
 * Static-owned public URLs. Hand-written HTML under public/; no React route.
 * `file` is relative to public/ and is what page-ownership.test.mjs checks.
 */
export const STATIC_OWNED = [
  { path: "/faq",               file: "faq/index.html",               priority: "0.8", changefreq: "monthly" },
  // `redirectOnly`: App.jsx keeps a /dmca route, but it renders nothing — it
  // just sets window.location to the static file. That is a safety net for a
  // client-side navigation, NOT a second document competing for the URL, so it
  // does not count as double ownership. Any route flagged this way must render
  // null and do nothing but redirect; page-ownership.test.mjs enforces that.
  { path: "/dmca",              file: "dmca.html",                    priority: "0.3", changefreq: "yearly", redirectOnly: true },

  // The five per-tool comparisons, all in directory form so they share one
  // shape. Each is linked from the /vs/compare table.
  { path: "/vs/browse-ai",      file: "vs/browse-ai/index.html",      priority: "0.7", changefreq: "monthly" },
  { path: "/vs/clay",           file: "vs/clay/index.html",           priority: "0.7", changefreq: "monthly" },
  { path: "/vs/firecrawl",      file: "vs/firecrawl/index.html",      priority: "0.7", changefreq: "monthly" },
  { path: "/vs/apify",          file: "vs/apify/index.html",          priority: "0.7", changefreq: "monthly" },
  { path: "/vs/phantombuster",  file: "vs/phantombuster/index.html",  priority: "0.7", changefreq: "monthly" },
];

/**
 * The generated help site. Owned by docs/build-help.mjs, which renders it from
 * docs/DatIQ-User-Guide.md and docs/DatIQ-Developer-API.md — so it is neither
 * React-owned nor hand-written, and editing the HTML is always wrong.
 * Listed here so the sitemap includes it.
 */
export const HELP_INDEX = { path: "/help/", file: "help/index.html", priority: "0.7", changefreq: "monthly" };

/**
 * Signed-in application prefixes. noindex, never prerendered, canonical
 * stripped. Kept in sync by hand with three other places, deliberately — each
 * defends a different layer and any one of them alone is insufficient:
 *   * netlify.toml X-Robots-Tag headers  (works without JS — the real defence)
 *   * the inline guard in index.html      (belt-and-braces for JS crawlers)
 *   * public/robots.txt Disallow lines    (polite crawlers, pre-fetch)
 */
export const PRIVATE_PREFIXES = [
  "/admin",
  "/dashboard",
  "/account",
  "/preview",
  "/batch",
  "/schedules",
  "/discoverability",
  "/workspace",
  // Intelligence Workflows (PRD 3, 4, 5). Each is a signed-in-only workspace
  // holding a customer's own account lists, competitor watchlists and routing
  // rules. They were shipped without being added here, so they were indexable.
  // NOTE the shareable-report route /r/:slug is deliberately NOT listed: its
  // `public` visibility state is MEANT to be indexable, so Report.jsx writes
  // the robots meta per report instead of a blanket disallow here.
  "/lists",
  "/watchlists",
  "/rules",
  "/workflows",
  "/collections",
  "/payment",
  "/reset-password",
  "/onboarding",
];

/**
 * Permanent redirects. Every URL that used to exist and now lives elsewhere.
 * Mirrored in netlify.toml; page-ownership.test.mjs asserts they match, so a
 * URL cannot be retired here without the redirect actually shipping.
 */
export const REDIRECTS = [
  // The homepage's prerendered output lives at public/home/index.html so it
  // cannot clobber Vite's entry (see the "/" entry above). Netlify serves it at
  // `/` via a 200 rewrite; this makes the helper path itself a dead end for
  // humans, and netlify.toml noindexes it for crawlers. Belt and braces: the
  // generated file's own canonical already points at https://datiq.app/.
  { from: "/home", to: "/" },
  // The duplicate Firecrawl page: public/vs/firecrawl.html AND
  // public/vs/firecrawl/index.html both existed and both served.
  { from: "/vs/firecrawl.html", to: "/vs/firecrawl" },
  // Normalised into directory form to match the other three comparisons.
  { from: "/vs/apify.html", to: "/vs/apify" },
  { from: "/vs/phantombuster.html", to: "/vs/phantombuster" },
  // The hub moved from a hand-written file to a React route.
  { from: "/vs/compare.html", to: "/vs/compare" },
  // Merged into the consolidated FAQ.
  { from: "/what-is-datiq", to: "/faq" },
  // build-help.mjs names pages after the section TITLE, so retitling section 14
  // to "Troubleshooting" moved this one file. The section NUMBER is unchanged,
  // so /help/15-* and /help/16-* keep their URLs.
  // Points at 15-, not 14-, because 14-troubleshooting.html ITSELF now
  // redirects to 15-. Leaving it would create a two-hop chain, which browsers
  // follow but crawlers discount.
  { from: "/help/14-faq-and-troubleshooting.html", to: "/help/21-troubleshooting.html" },
  // The Discoverability guide was inserted as section 11, shifting the six
  // sections after it by one. Their old URLs are in the published sitemap and
  // linked from blog posts; a module about discoverability that broke its own
  // indexed URLs would be a poor advertisement for it.
  { from: "/help/11-plans-usage-and-billing.html", to: "/help/18-plans-usage-and-billing.html" },
  { from: "/help/12-accounts-trial-and-sign-in.html", to: "/help/19-accounts-trial-and-sign-in.html" },
  { from: "/help/13-privacy-and-your-data.html", to: "/help/20-privacy-and-your-data.html" },
  { from: "/help/14-troubleshooting.html", to: "/help/21-troubleshooting.html" },
  { from: "/help/15-keyboard-shortcuts.html", to: "/help/22-keyboard-shortcuts.html" },
  { from: "/help/16-glossary.html", to: "/help/23-glossary.html" },
  // The six intelligence-workflow guides were inserted as sections 10-15,
  // shifting the eight sections after them by six. Those URLs are in the
  // published sitemap and linked from blog posts and the changelog, so each
  // gets a permanent redirect. The pre-existing redirects just above were
  // repointed at the NEW numbers rather than at the intermediate ones, for the
  // reason recorded on the 14-faq entry: a two-hop chain is discounted.
  { from: "/help/10-exports-and-sharing.html", to: "/help/16-exports-and-sharing.html" },
  { from: "/help/11-discoverability-seo-aeo-and-geo-audits.html", to: "/help/17-discoverability-seo-aeo-and-geo-audits.html" },
  { from: "/help/12-plans-usage-and-billing.html", to: "/help/18-plans-usage-and-billing.html" },
  { from: "/help/13-accounts-trial-and-sign-in.html", to: "/help/19-accounts-trial-and-sign-in.html" },
  { from: "/help/14-privacy-and-your-data.html", to: "/help/20-privacy-and-your-data.html" },
  { from: "/help/15-troubleshooting.html", to: "/help/21-troubleshooting.html" },
  { from: "/help/16-keyboard-shortcuts.html", to: "/help/22-keyboard-shortcuts.html" },
  { from: "/help/17-glossary.html", to: "/help/23-glossary.html" },
  // These were React <Navigate> redirects in App.jsx pointing at /vs/browse-ai.
  // That route is being deleted (the page is static-owned now), so they have to
  // become server-side redirects or they would dead-end in NotFound.
  { from: "/compare", to: "/vs/browse-ai" },
  { from: "/compare/*", to: "/vs/browse-ai" },
];

/** Convenience: every public URL, in sitemap order. */
export function allPublicRoutes() {
  return [...REACT_OWNED, ...STATIC_OWNED, HELP_INDEX];
}

/**
 * The React-owned routes that actually get a generated file. Excludes `/`
 * for the reason documented on its entry above.
 */
export function prerenderableRoutes() {
  return REACT_OWNED.filter((r) => r.prerender !== false);
}

/**
 * public/<dir>/index.html for a prerenderable route. Throws on "/" rather than
 * returning "index.html", because that path would clobber Vite's entry point
 * and a silent return here is how that bug would reach a build.
 */
export function generatedFileFor(routePath) {
  const route = REACT_OWNED.find((r) => r.path === routePath);
  // An explicit `file` is the ONLY way a route may land somewhere other than
  // <path>/index.html. `/` uses it to reach public/home/index.html.
  if (route?.file) return route.file;

  const slug = routePath.replace(/^\/+/, "").replace(/\/+$/, "");
  const derived = `${slug}/index.html`;
  // Still fatal, and deliberately so: an empty slug means public/index.html,
  // which Vite copies over dist/index.html and destroys the app's entry point.
  // A silent return here is how that bug would reach a build.
  if (slug === "") {
    throw new Error(
      `generatedFileFor('${routePath}') would write public/index.html and ` +
      "overwrite Vite's build entry. Give the route an explicit `file`. See site-routes.mjs.",
    );
  }
  return derived;
}
