-- 0038_field_provenance.sql
-- Phase 0 of docs/INTELLIGENCE-WORKFLOWS-IMPLEMENTATION-PLAN.md — the spine.
--
-- ── WHY FIELD-LEVEL STORAGE, NOT JUST A _provenance BLOB ────────────────────
-- src/lib/provenanceService.js already attaches a `_provenance` object to an
-- extraction in memory, and 0006_provenance.sql stores it as a jsonb column.
-- That is enough to render a badge. It is NOT enough for either of the two
-- phases that follow:
--   PRD 3 needs to FILTER and SORT a list of 500 accounts by the confidence of
--          one field, and re-run only the rows whose fields are stale.
--   PRD 4 needs to DIFF one field against its previous value across runs.
-- Both are queries across runs. A blob per extraction cannot answer either
-- without reading every blob.
--
-- ── THE observed / inferred / ai_generated DISTINCTION IS THE PRODUCT ───────
-- The BRD is explicit: every important output must disclose "whether a field
-- was explicitly observed, inferred, or generated by AI", and PRD 4 requires
-- that an AI explanation "must distinguish FACT from INTERPRETATION".
--
-- Making `method` a CHECK-constrained column rather than a convention is what
-- turns that from a prompt-discipline aspiration into something the schema
-- guarantees. A field the AI wrote can never be silently rendered as a
-- verified fact about the source page, because the two are different values in
-- a constrained column and the renderer branches on it.
--
--   observed      the value is literally present in the fetched document
--   inferred      derived from observed content — still a claim ABOUT the source
--   ai_generated  net-new prose the model wrote — NOT a claim about the source
--   user_provided a human supplied or confirmed it (PRD 3's review queue)
--
-- ── confidence IS NULLABLE, AND NULL IS NOT ZERO ────────────────────────────
-- This is the discoverability module's founding rule, carried over verbatim:
-- an unmeasured signal is EXCLUDED and its weight redistributed, never scored
-- zero. The CHECK below permits NULL and permits 0..1, so "we could not
-- measure this" and "we measured this and it scored nothing" stay distinct
-- values. In PRD 3 that distinction is the difference between "headcount
-- unknown" and "0 employees, poor ICP fit" — the second would silently poison
-- every ranked call list the product exists to produce.
--
-- Adds 2 tables, 0 functions, 0 triggers.

-- ── the normalized value store ──────────────────────────────────────────────
create table if not exists public.extracted_fields (
  id          uuid primary key default gen_random_uuid(),
  run_id      text references public.template_runs(id) on delete cascade,
  -- Canonical entity this field describes (normalized domain, e.g.
  -- 'stripe.com'). This is the join key that lets PRD 4 diff the same field
  -- across two runs, and PRD 3 dedupe two spellings of one company.
  entity_key  text,
  field_path  text not null,                        -- 'pricing.tiers[0].amount'
  -- PRD 3's recommended first schema categories: identity, firmographics,
  -- commercial, gtm, people, technology, signals, qualification, governance.
  field_group text,
  value_text   text,
  value_json   jsonb,
  value_number numeric,
  -- NULL = not measured. See the header — this is load-bearing.
  confidence  numeric,
  observed_at timestamptz,
  created_at  timestamptz not null default now(),
  constraint extracted_fields_confidence_chk
    check (confidence is null or (confidence >= 0 and confidence <= 1)),
  constraint extracted_fields_run_path_uniq unique (run_id, field_path)
);

create index if not exists extracted_fields_entity_idx
  on public.extracted_fields (entity_key, field_path, observed_at desc)
  where entity_key is not null;
create index if not exists extracted_fields_run_idx
  on public.extracted_fields (run_id);
create index if not exists extracted_fields_group_idx
  on public.extracted_fields (field_group) where field_group is not null;

-- ── where each value came from and how it was produced ──────────────────────
create table if not exists public.field_provenance (
  id                uuid primary key default gen_random_uuid(),
  field_id          uuid not null references public.extracted_fields(id) on delete cascade,
  -- Which fetched page. ON DELETE SET NULL: losing the source record must not
  -- erase the field — an orphaned value with a recorded URL is still evidence.
  source_id         uuid references public.template_run_sources(id) on delete set null,
  source_url        text,
  method            text not null,
  extractor         text,                           -- 'firecrawl' | 'ai:gemini-2.0-flash' | 'rule:pricing_v1'
  extractor_version text,
  -- Points back into workflow_templates.prompt_bundle, so a field produced by
  -- a prompt can always be traced to the exact prompt text that produced it.
  prompt_ref        text,
  observed_at       timestamptz,
  created_at        timestamptz not null default now(),
  constraint field_provenance_method_chk
    check (method in ('observed', 'inferred', 'ai_generated', 'user_provided'))
);

create index if not exists field_provenance_field_idx
  on public.field_provenance (field_id);
create index if not exists field_provenance_method_idx
  on public.field_provenance (method);

-- ── RLS: service key only ───────────────────────────────────────────────────
alter table public.extracted_fields  enable row level security;
alter table public.field_provenance  enable row level security;

do $$ begin
  if not exists (select 1 from pg_policies where tablename = 'extracted_fields' and policyname = 'service full access') then
    execute 'create policy "service full access" on public.extracted_fields
             for all to service_role using (true) with check (true)';
  end if;
  if not exists (select 1 from pg_policies where tablename = 'field_provenance' and policyname = 'service full access') then
    execute 'create policy "service full access" on public.field_provenance
             for all to service_role using (true) with check (true)';
  end if;
end $$;
