-- 0045_workflow_engines.sql
--
-- Schema the three execution engines need (PRD 3, 4, 5). Additive only: no
-- table is dropped, no column is removed, no data is rewritten.
--
-- Follows the service-role-only RLS convention 0044 restored. Nothing here
-- grants anything to anon.

-- ── 1. Field-level provenance on an enriched account row ────────────────────
--
-- The BRD makes provenance a product feature, not metadata: every important
-- output should disclose its source URL, extraction timestamp, method, and
-- "whether a field was explicitly observed, inferred, or generated by AI".
--
-- `enriched_data` holds the VALUES; this holds, per field, how we came to
-- believe them:
--   { "industry": { "method": "inferred", "source": "https://…", "confidence": 0.8 } }
--
-- It is separate from `confidence_score` (a single row-level number) because a
-- row is rarely uniformly trustworthy — a company name read off the page and an
-- industry inferred by a model are not the same kind of claim, and collapsing
-- them into one number is what let the previous enricher stamp 0.95 on
-- fabricated firmographics.
alter table public.list_records
  add column if not exists provenance jsonb not null default '{}'::jsonb;

-- ── 2. Watchlist crawl bookkeeping ──────────────────────────────────────────
--
-- `watchlists.last_run_at` lets the monitor answer "when did this watchlist
-- last actually run?" without scanning every target, and gives the UI something
-- truthful to show instead of implying a cadence that has never fired.
alter table public.watchlists
  add column if not exists last_run_at timestamptz;

-- Why a page stopped being monitored. A robots.txt refusal is a standing
-- decision, not a transient error, and must be distinguishable from "the fetch
-- failed this once" — otherwise the crawler retries a disallowed host hourly
-- for ever, which is exactly the behaviour our own /blog promises we do not
-- have.
alter table public.monitored_pages
  add column if not exists paused_reason text;

-- ── 3. Rule execution retry accounting ──────────────────────────────────────
--
-- PRD 5 lists "retry failed actions" as a Must. A retry needs somewhere to
-- record that it IS a retry, or a transient Slack 503 is indistinguishable from
-- a rule that has failed eleven times and should be reported to its owner.
alter table public.rule_executions
  add column if not exists attempt integer not null default 1;

alter table public.rule_executions
  add column if not exists next_retry_at timestamptz;

create index if not exists rule_executions_retry_idx
  on public.rule_executions (next_retry_at)
  where next_retry_at is not null;

-- ── 4. Keep the 0044 posture ────────────────────────────────────────────────
-- Adding a column cannot change a policy, but asserting it here means a future
-- reader of this file sees the invariant rather than having to go and check.
do $$
declare t text;
begin
  foreach t in array array['list_records','watchlists','monitored_pages','rule_executions']
  loop
    execute format('alter table public.%I enable row level security', t);
    execute format('revoke all on public.%I from anon', t);
    execute format('revoke all on public.%I from authenticated', t);
    execute format('grant all on public.%I to service_role', t);
  end loop;
end $$;
