// AuditHeader — what page this report is about, and what it says.
//
// ── WHY THIS EXISTS ────────────────────────────────────────────────────────
// Opening a historical audit from the History screen produced a wall of scores
// with no indication of WHICH page they described. The composer above shows the
// URL you are about to audit, not the one you are looking at — so a report
// reached from history was anonymous, and comparing two of them meant reading
// the browser's address bar.
//
// ── THE SUMMARY IS OPTIONAL, DELIBERATELY ──────────────────────────────────
// It is generated by a model, lazily, on first view. If that fails the header
// still renders the identity block — the URL, when it ran, the profile, the
// device, the page type — because those are the part that must never be
// missing. A report with no summary is a report; a report that failed to load
// is not.

import { useEffect, useState } from "react";
import Icon from "../Icon.jsx";
import FaviconDot from "../FaviconDot.jsx";
import { hostOf } from "../../lib/utils.js";
import { discoverability } from "../../lib/discoverability/discoverabilityClient.js";

function when(iso) {
  if (!iso) return null;
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return null;
  return d.toLocaleString(undefined, {
    day: "numeric", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit",
  });
}

export default function AuditHeader({ audit }) {
  // Seeded from the audit itself, so an already-summarised report shows its
  // summary on first paint with no request at all.
  const [summary, setSummary] = useState(audit?.summary || null);
  const [loading, setLoading] = useState(false);
  const [unavailable, setUnavailable] = useState(false);

  const auditId = audit?.auditId;

  useEffect(() => {
    setSummary(audit?.summary || null);
    setUnavailable(false);
  }, [auditId, audit?.summary]);

  useEffect(() => {
    if (!auditId || summary) return;
    let alive = true;
    setLoading(true);
    discoverability.summary(auditId)
      .then((r) => {
        if (!alive) return;
        if (r?.summary) setSummary(r.summary);
        else setUnavailable(true);
      })
      // A failed summary is not a failed report. Swallow it and show the facts.
      .catch(() => { if (alive) setUnavailable(true); })
      .finally(() => { if (alive) setLoading(false); });
    return () => { alive = false; };
  }, [auditId, summary]);

  if (!audit) return null;

  const url = audit.target?.url || "";
  const host = hostOf(url) || url;
  const ran = when(audit.audit?.created_at || audit.meta?.startedAt);

  const facts = [
    ran,
    audit.target?.audit_profile && `${audit.target.audit_profile} profile`,
    audit.target?.device_profile,
    audit.target?.page_type_label || audit.target?.page_type,
  ].filter(Boolean);

  return (
    <section className="dsc-audit-header" aria-label="Audited page">
      <div className="dsc-audit-header-id">
        <FaviconDot url={url} size={26} />
        <div className="dsc-audit-header-url">
          {/* The full URL, not just the host: two audits of the same site are
              the commonest pair to compare, and the path is the only thing
              that tells them apart. */}
          <a href={url} target="_blank" rel="noopener noreferrer nofollow" title={url}>
            {url || host}
            <Icon name="external-link" size={12} />
          </a>
          <div className="dsc-audit-header-facts">{facts.join("  ·  ")}</div>
        </div>
      </div>

      {summary ? (
        <p className="dsc-audit-summary">{summary}</p>
      ) : loading ? (
        <p className="dsc-audit-summary dsc-audit-summary-loading">
          <Icon name="loader" size={13} className="spin" /> Summarising this audit…
        </p>
      ) : unavailable ? (
        // Says what is missing rather than pretending nothing was meant to be
        // here. The scores below are unaffected and that is worth stating.
        <p className="dsc-audit-summary dsc-audit-summary-muted">
          A written summary is not available for this audit. The findings below are complete.
        </p>
      ) : null}
    </section>
  );
}
