// AuditHeader — what page this report is about, and what it says.
//
// ── WHY THIS EXISTS ────────────────────────────────────────────────────────
// Opening a historical audit from the History screen produced a wall of scores
// with no indication of WHICH page they described. The composer above shows the
// URL you are about to audit, not the one you are looking at — so a report
// reached from history was anonymous, and comparing two of them meant reading
// the browser's address bar.
//
// ── THE SUMMARY IS OPTIONAL, DELIBERATELY ──────────────────────────────────
// It is generated by a model, lazily, on first view. If that fails the header
// still renders the identity block — the URL, when it ran, the profile, the
// device, the page type — because those are the part that must never be
// missing. A report with no summary is a report; a report that failed to load
// is not.

import { useEffect, useState } from "react";
import Icon from "../Icon.jsx";
import FaviconDot from "../FaviconDot.jsx";
import { hostOf } from "../../lib/utils.js";
import { discoverability } from "../../lib/discoverability/discoverabilityClient.js";
import { AUDIT_PROFILES } from "../../lib/discoverability/auditProfiles.js";
import { PRIMARY_GOALS } from "../../lib/discoverability/intakeModel.js";

function when(iso) {
  if (!iso) return null;
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return null;
  return d.toLocaleString(undefined, {
    day: "numeric", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit",
  });
}

export default function AuditHeader({
  audit, diff = null, framework = "overall", onFrameworkChange = null, workspaceId = null,
}) {
  // Seeded from the audit itself, so an already-summarised report shows its
  // summary on first paint with no request at all.
  const [summary, setSummary] = useState(audit?.summary || null);
  const [loading, setLoading] = useState(false);
  const [unavailable, setUnavailable] = useState(false);

  const auditId = audit?.auditId;

  useEffect(() => {
    setSummary(audit?.summary || null);
    setUnavailable(false);
  }, [auditId, audit?.summary]);

  useEffect(() => {
    if (!auditId || summary) return;
    let alive = true;
    setLoading(true);
    discoverability.summary(auditId, { workspaceId })
      .then((r) => {
        if (!alive) return;
        if (r?.summary) setSummary(r.summary);
        else setUnavailable(true);
      })
      // A failed summary is not a failed report. Swallow it and show the facts.
      .catch(() => { if (alive) setUnavailable(true); })
      .finally(() => { if (alive) setLoading(false); });
    return () => { alive = false; };
  }, [auditId, summary, workspaceId]);

  if (!audit) return null;

  const url = audit.target?.url || "";
  const host = hostOf(url) || url;
  const ran = when(audit.audit?.created_at || audit.meta?.startedAt);

  // ── WHY THE PROFILE IS SHOWN WITH ITS REASON ─────────────────────────────
  // A reader who disagrees with the lens needs to know whether they chose it,
  // whether their goal chose it, or whether we guessed it from their markup.
  // Those are three different claims, and only one of them is ours to defend.
  // Same rule the evidence envelope enforces one layer down: an observed fact
  // and an inference must never be presented as the same kind of thing.
  const profile = audit.target?.audit_profile;
  const profileLabel = profile && (AUDIT_PROFILES[profile]?.label || profile);
  const because = {
    goal: "from your goal",
    inferred: "read from the page",
    // 'explicit' needs no gloss — the reader made the choice — and 'default'
    // is the absence of one, which the goal line already implies.
    explicit: null,
    default: null,
  }[audit.target?.audit_profile_source] || null;

  const goal = audit.intake?.primary_goal;
  const goalLabel = goal && (PRIMARY_GOALS[goal]?.label || goal);

  const facts = [
    ran,
    // Audits that predate migration 0049 carry no goal, and nothing is shown
    // for them rather than a placeholder claiming one.
    goalLabel && `for ${goalLabel}`,
    profileLabel && `${profileLabel} profile${because ? ` (${because})` : ""}`,
    audit.target?.device_profile,
    audit.target?.page_type_label || audit.target?.page_type,
  ].filter(Boolean);

  // ── §7.12 · the baseline delta ───────────────────────────────────────────
  //
  // ⚠️ SHOWN ONLY WHEN THE TWO AUDITS ARE COMPARABLE. `auditDiff` refuses a
  // cross-version comparison outright, and a headline "+4.2" that quietly mixed
  // two scoring models would be the single most-screenshotted wrong number in
  // the product. When it refuses, the header says why rather than going blank —
  // a missing delta with no explanation reads as "nothing changed".
  const overall = diff?.frameworks?.overall || null;
  const deltaNode = (() => {
    if (!diff) return null;
    if (diff.comparable === false || overall?.comparable === false) {
      return (
        <span className="dsc-audit-delta is-unknown" title={diff.reason || overall?.reason || ""}>
          not comparable to the baseline
        </span>
      );
    }
    if (!Number.isFinite(overall?.change)) return null;
    const up = overall.change > 0;
    const flat = Math.abs(overall.change) < 0.5;
    return (
      <span className={`dsc-audit-delta${flat ? "" : up ? " is-up" : " is-down"}`}>
        <Icon name={flat ? "minus" : up ? "trending-up" : "trending-down"} size={13} />
        {flat ? "no change" : `${up ? "+" : ""}${overall.change} vs baseline`}
      </span>
    );
  })();

  return (
    <section className="dsc-audit-header" aria-label="Audited page">
      <div className="dsc-audit-header-id">
        <FaviconDot url={url} size={26} />
        <div className="dsc-audit-header-url">
          {/* The full URL, not just the host: two audits of the same site are
              the commonest pair to compare, and the path is the only thing
              that tells them apart. */}
          <a href={url} target="_blank" rel="noopener noreferrer nofollow" title={url}>
            {url || host}
            <Icon name="external-link" size={12} />
          </a>
          <div className="dsc-audit-header-facts">{facts.join("  ·  ")}</div>
        </div>
        {deltaNode}
      </div>

      {/* ── §7.12 · the goal selector ────────────────────────────────────────
          ⚠️ THIS CHANGES THE LENS, NOT THE MATHS. All four framework views are
          always computed with identical weightings — the profile only decides
          which one leads — so switching here re-frames a report that is already
          complete. It never re-runs anything and never costs an audit, which is
          exactly why it can live in the header. */}
      {onFrameworkChange ? (
        <div className="dsc-audit-lens">
          <label className="dsc-audit-lens-label" htmlFor="audit-lens">Read as</label>
          <select
            id="audit-lens"
            className="dsc-audit-lens-select"
            value={framework}
            onChange={(e) => onFrameworkChange(e.target.value)}
          >
            <option value="overall">Overall</option>
            <option value="seo">SEO</option>
            <option value="aeo">Answer engines</option>
            <option value="geo">Generative engines</option>
          </select>
          <span className="dsc-audit-lens-note">
            Switching the lens re-frames this report. It does not re-run the audit.
          </span>
        </div>
      ) : null}

      {summary ? (
        <p className="dsc-audit-summary">{summary}</p>
      ) : loading ? (
        <p className="dsc-audit-summary dsc-audit-summary-loading">
          <Icon name="loader" size={13} className="spin" /> Summarising this audit…
        </p>
      ) : unavailable ? (
        // Says what is missing rather than pretending nothing was meant to be
        // here. The scores below are unaffected and that is worth stating.
        <p className="dsc-audit-summary dsc-audit-summary-muted">
          A written summary is not available for this audit. The findings below are complete.
        </p>
      ) : null}
    </section>
  );
}
